### ISSUE TITLE
Missing example where the DOM is updated twice in a test case, maybe?

### ISSUE THREAD

**Issue by renatoliveira** [trailheadapps/lwc-recipes#100]
I think that the closest example for the use case I found is the `apexImperativeMethodWithParams` example, where the user clicks a button and then something happens on the server. However, the current example serves for a component that has the button displayed all the time, not being conditionally shown within a template tag.

I'd like to see an example of a component that fetches data from the server, so it knowns wether to display the button or not, and then if the user clicks the button, it fires another server action.

I have tried chaining the Promise that is returned at the end of the test using `.then`, but it doesn't seem to work that way. I don't know how specific those tests conditions (using promises, refreshing the DOM, etc) are for the LWC framework, so an example would come in handy.

This question/issue is the same I mentioned on the question I made on SFSE, [here](https://salesforce.stackexchange.com/q/261662/18269).

**Comment by muenzpraeger** [comment]
@renatoliveira This is less a thing of LWC, but more how you have to handle microtasks in Jest.

In your example you're clicking the button. That's one task. But firing the event comes _after_ that. So it would be another `then` for example.

This article is really great to understand the mechanics.

https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/

**Comment by renatoliveira** [comment]
Thanks for the article @muenzpraeger!

I think I somewhat get the difference between tasks and microtasks now, but I do not follow how those apply to the test cases. Are you saying that I have to chain the events in the test case with `.then`?

As far as I understood, the Promise returned at the end of the test serves to update the DOM (simulating the component being loaded on the screen). I can mock any server-side calls that the component makes when loaded right in the scope where the promise is resolved.

    return Promise.resolve(() => { console.log('Yay I can assert the server-side mocks were called!') })
    // And I can also test if specific elements were rendered, too

But then, if I use the `.click` method after querying a button (that is conditionally displayed on screen), I can't verify the servers-side call (that the button fires).

Please bear with me for a minute with this example:

```javascript
it('should display a toast when the check-in button is pressed', () => {
    // apex method called when the check-in button is clicked
    doCheckIn.mockResolvedValue(true)

    // apex method that the component fires on load, to verify that it can
    // display the check-in button on the screen
    isCheckInAvailable.mockResolvedValue(true)

    const recordId = '00Q3F000002StmkUAC'
    const comp = createElement('c-checkin', {
        is: CheckIn
    })
    comp.recordId = recordId

    document.body.appendChild(comp)

    const toastEventHandler = jest.fn()
    comp.addEventListener(ShowToastEventName, toastEventHandler)

    return Promise.resolve(() => {
        // checkInEnabled is a property that is used on the `disabled` attribute
        // on the lightning-button
        expect(comp.checkInEnabled).toBe(true)

        // query the button, and click it
        comp.shadowRoot.querySelector('lightning-button[label="Check-IN"]').click()
    }).then(() => {

        // after click-ing the button, I expect at least that the `doCheckIn`
        // apex method is called
        expect(doCheckIn).toHaveBeenCalled()
    }).then(() => {
        // then I can assert that the toast is called, since I'm returning the value
        // which fires the toast event, no?
        expect(toastEventHandler).toHaveBeenCalled()
    })
})
```

On the line I assert that `doCheckIn` was called, Jest tells me that it wasn't, even though it happened after the promise resolves.

I would really appreciate if you could shed some light on this. Surely this would help a lot more people in the near future as well.

**Comment by muenzpraeger** [comment]
Sorry for the late reply, @renatoliveira, I was traveling a bit over the last days.

Yes - you have to chain multiple `then()` in these cases.

For you example:
The Apex method `doCheckIn` is a promise. You _started_ the action using your `lightning-button` - but that doesn't mean that it already got executed, as it's async. You can see in the Apex related recipes that we [flush the promises for simplicity](https://github.com/trailheadapps/lwc-recipes/blob/bb2f9e4438ef28a7b061ba74a3fa0ff1b0af549b/force-app/main/default/lwc/miscRestApiCall/__tests__/miscRestApiCall.test.js#L70) to actually wait for the execution.

**Comment by AllanOricil** [comment]
@renatoliveira Could you post the solution? I have the same problem.

**Comment by AllanOricil** [comment]
I made it work. For everyone that needs an example:

````js

 function flushPromises() {
        // eslint-disable-next-line no-undef
        return new Promise(resolve => setImmediate(resolve));
    }

it('done button dispatches an event with the new changes on click', ()=>{
        const dceDragAndDropCheckboxInputGroup = element.shadowRoot.querySelector('c-dce-drag-and-drop-checkbox-input-group');
        dceDragAndDropCheckboxInputGroup.dispatchEvent(
            new CustomEvent("change", {
                detail: 
                    { 
                        entries: 
                            [
                                {
                                    label: 'Column 2',
                                    isSelected: false
                                },
                                {
                                    label: 'Column 3',
                                    isSelected: false,
                                },
                                {
                                    label: 'Column 1',
                                    isSelected: false
                                }
                            ] 
                    }
            })
        );

        const handler = jest.fn();
        element.addEventListener('newcolumnsorder', handler);
       
        return flushPromises()
                .then(() => {
                    const doneButton = element.shadowRoot.querySelector('lightning-button');
                    expect(doneButton.disabled).toEqual(false);
                    doneButton.click();
                })
                .then(() => {
                    expect(handler).toHaveBeenCalled();
                    const event = handler.mock.calls[0][0];
                    expect(event.detail.columns[0].label).toEqual('Column 2');
                    expect(event.detail.columns[1].label).toEqual('Column 3');
                    expect(event.detail.columns[2].label).toEqual('Column 1');
                    expect(event.detail.columns[0].isSelected).toEqual(false);
                    expect(event.detail.columns[1].isSelected).toEqual(false);
                    expect(event.detail.columns[2].isSelected).toEqual(false);
                })

    });
````
