### ISSUE TITLE
MutationObserver listener not being fired on lwc:dom="manual"

### ISSUE THREAD

**Issue by angelsalazar** [trailheadapps/lwc-recipes#101]
### Summary

I am building a component using lwc:dom="manual" so I can create the nodes dynamically and using the native class MutationObserver to keep in track the current amount of elements 

### Steps To Reproduce:

1. create a LW component and set the lwc:dom="manual" directive on a node (div, ul, tbody).
2. observe the node marked with lwc:dom directive for changes in the chidList property using the MutationObserver native class.
3. Observer callback is never fired

### Expected result

MutationObserver callback should be fired when nodes are either added or removed from the node being observed

### Actual result

MutationObserver callback is not fired and it does not throw any error. 

### Additional information

I have created a minimalist version of what I am trying to accomplish that illustrate the problem.

testTable.html
```html
<template>

    <div class="global-actions">
        <button onclick={addRow}>add</button>
    </div>

    <div>
        current rows: {count}
    </div>

    <div class="table">
        <div class="head">
            <div class="row">
                <div class="cell">Name</div>
                <div class="cell">Action</div>
            </div>
        </div>
        <div 
            lwc:dom="manual"
            class="body">
        </div>
    </div>
</template>
```

testTable.css

```javascript
import { LightningElement, track } from 'lwc';

export default class TestTable extends LightningElement {

    @track count = 0;

    _body = null;
    _index = 1;
    _unsubscribe = null;
    obeserving = false;

    get body() {
        if (this._body === null) {
            this._body = this.template.querySelector('div.body');
        }

        return this._body;
    }

    renderedCallback() {
        if (this.obeserving) { return; }
        this.obeserving = true;
        this.onChildrenChange();
        this._unsubscribe = this.setObserver();
    }

    disconnectedCallback() {
        this._unsubscribe && this._unsubscribe();
    }
    
    onChildrenChange() {
        this.count = this.body.children.length;
        //console.log('children updated');
        //console.log(this.body.children.length);
    }

    setObserver() {
        const observer = new MutationObserver(this.onChildrenChange.bind(this));
        observer.observe(this.body, {
            childList: true
        });

        return () => {
            observer.disconnect();
        }
    }

    addRow() {
        const tr = document.createElement('div');
        const td1 = document.createElement('div');
        const td2 = document.createElement('div');
        const button = document.createElement('button');

        tr.className = 'row';

        button.innerText = 'Delete';
        button.onclick = () => {
            tr.remove();
        }
        td1.className = 'cell';
        td1.innerText = 'Random ' + (this._index++);
        td2.className = 'cell';

        td2.appendChild(button);
        tr.appendChild(td1);
        tr.appendChild(td2);
        this.body.appendChild(tr);
    }
}
```
testTable.css

```css
:host {
    display: block;
}

:host .table {
    display: table;
}

:host .head {
    display: table-header-group;
}

:host .body {
    display: table-row-group;
}

:host .row {
    display: table-row;
}

:host .cell {
    display: table-cell;
}
```

I have also created a working example using the vanilla javascript, which you can find below

[Expected behavior](https://jsbin.com/foqukazupu/edit?html,js,output)

**Comment by ravijayaramappa** [comment]
@angelsalazar Tried your repro steps in the playground and it seems to work as expected. The observer callback is getting called. May be the repro steps is missing a piece?
https://developer.salesforce.com/docs/component-library/tools/playground/RWaFJAKkH/1/edit

**Comment by angelsalazar** [comment]
that's weird @ravijayaramappa
I forgot to mention that I am using a Developer Edition scratch org.

**Comment by muenzpraeger** [comment]
Yeah, the Playground doesn't use Lightning Locker, while your Developer Edition does. We're investigating.

**Comment by muenzpraeger** [comment]
@angelsalazar Can you try if your implementation works in a pre-release org?

**Comment by angelsalazar** [comment]
@muenzpraeger is there a way to create a pre-release org using sfdx?

**Comment by muenzpraeger** [comment]
I just tried in a pre-release org. Everything works as expected.

To use/get one with the CLI is pretty simple. You sign-up for a pre-release developer edition (like [here](https://www.salesforce.com/form/signup/prerelease-summer19/)), and then use that one as your dev hub.
