### ISSUE TITLE
Testing children passed to slot

### ISSUE THREAD

**Issue by angelsalazar** [trailheadapps/lwc-recipes#103]
### Summary

I wonder if this issue can be considered as a bug, but since I did not find a solution on the lwc docs I think it is.
is it possible to tests components that receives children using an `slot` element?
I have build a wizard component that I am not able to test because there is no way to pass the components as children.

### Steps To Reproduce:

1. create a component that receives children using `slot`
2. when testing it, try adding children using appendChild (I know this is not possible because it requires the `lwc:dom="manual"` directive, but my wizard does not expect to receive children programmatically but declaratively)

### Expected result

there should be way to test components that receive children using `slot` or a way to set
the `lwc:dom="manual"` programatically.

### Actual result

there is no way to test the case described above.

### Additional information

My workaround to this issue was to create a test demo component that renders the wizard and its wizard steps, but I feel lwc library should provide a way to test this scenario.

**Comment by muenzpraeger** [comment]
Please open an issue for this on the LWC Jest repo, if you thing that Jest testing functionality is missing. Thanks!

https://github.com/salesforce/sfdx-lwc-jest
