### ISSUE TITLE
Add Lightning Out recipe

### ISSUE THREAD

**Issue by neidenmark** [trailheadapps/lwc-recipes#115]
**What is missing from the application? Please describe.**
How to add Lightning Out components to a lwc.dev app.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by muenzpraeger** [comment]
Why would you want to use Lightning Out with an off-platform app?

**Comment by neidenmark** [comment]
To use i.e. Salesforce flow's. Working on a customer demo where we want to include this functionality.. but I want the demo to be built on lwc.dev..

**Comment by neidenmark** [comment]
ohh, i think i posted this in the wrong repo.. lwc-recipes-oss is the right one i guess,..
