### ISSUE TITLE
Event bubbling Example refreshes the Page  

### ISSUE THREAD

**Issue by sudikrt** [trailheadapps/lwc-recipes#116]
I m trying event bubbling, But when I click on contact it Refreshes the page instead of calling throwing an event

**Comment by muenzpraeger** [comment]
@sudikrt can you please provide more information? Are you using one of the recipes from this repo, or did you build your own implementation?

**Comment by sudikrt** [comment]
@muenzpraeger I am using the same recipe provided in this repo 'EventBubbling' example

**Comment by muenzpraeger** [comment]
Did you do modifications to the overall project? Like, do you have other parent components that react on events? The recipe sends a bubbled event (which is custom), so if you have any additional logic added that may be the root cause.

**Comment by sudikrt** [comment]
I don't have other parent components,

**Comment by muenzpraeger** [comment]
Interesting. Although, as said before, the recipe doesn’t call or interact with anything that could cause this.

Can you reproduce it across multiple browsers?
