### ISSUE TITLE
Sample showing Apex continuations

### ISSUE THREAD

**Issue by kevinv11n** [trailheadapps/lwc-recipes#117]
**What is missing from the application? Please describe.**
 I'd like to see an implementation of Apex continuations. See https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.apex_continuations for documentation.

**Describe the solution you'd like**
- An Apex class that uses a continuation
- An LWC component that allows me to manually trigger the continuation
- An LWC component that uses `@wire` to trigger the continuation

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by pranayjswl007** [comment]
Would you mind adding Apex Unit Testing scenario to cover Continuation Testing in static context?
https://salesforce.stackexchange.com/questions/262211/continuation-apex-unit-testing-lightning

**Comment by muenzpraeger** [comment]
We discussed adding an Apex Continuation example, and decided to not implement it.

It's primarily an Apex-based pattern the invocation/handling on the LWC side is similar to regular Apex calls, which are covered well in the existing recipes.
