### ISSUE TITLE
Is there a way to retrieve contact record with an email instead of record id or id in LWC

### ISSUE THREAD

**Issue by madhu231** [trailheadapps/lwc-recipes#121]
## My Use Case
 We are working on a user onboarding stuff in Salesforce. In this use case, we will check whether user contact already exists in the salesforce, if not we will create it. 

When it comes to validating the contact I will have an email with me, but not record id. 
So, how I can get the contact record using email?
please provide your ideas and suggestions on this.

sample code which I'm trying is here, is there a way to use another field instead of recordid
`@wire(getRecord, { recordId: '$usremail', fields: FIELDS })
    contact;`

**Comment by muenzpraeger** [comment]
You can't. You'll have to write Apex for that.

For future reference these kind of questions should be posted on the [Salesforce Developer Forums](https://developer.salesforce.com/forums), or on [Salesforce Stack Exchange](https://salesforce.stackexchange.com/), as they are not related to Recipes.

**Comment by madhu231** [comment]
Thanks @muenzpraeger
