### ISSUE TITLE
Getting } expectedcss(css-rcurlyexpected in chartBar LWC

### ISSUE THREAD

**Issue by rohitji95** [trailheadapps/lwc-recipes#122]
### Getting an error while creating chartBar LWC.
In chartBar HTML, I have used the following code
   ` <div class="bar" style={style} ></div>`
in JS .-

```
@api percentage;
get style() {
        return 'width: ${this.percentage}%';
    }

```

Getting 2 errors on the html file.
1. } expectedcss(css-rcurlyexpected

2. at-rule or selector expectedcss(css-ruleorselectorexpected)

**Comment by muenzpraeger** [comment]
That‘s an issue with the CSS validation of VS Code and not related to `lwc-Recipes`.

**Comment by rohitji95** [comment]
It is still showing same error even if I have removed CSS class.
      <div>{percentage}%</div>
    <div style={style} ></div>
Could you pls help me to troubleshoot this issue.

**Comment by muenzpraeger** [comment]
There’s nothing to troubleshoot. VS Code sees anything that’s not in quotation marks as a value for the `style` attribute as invalid. It’s an IDE thing.

**Comment by rohitji95** [comment]
ok Thanks muenzpraeger. The code gets deployed from VSCode even showing errors. Strange!!
Actually, I was assuming, my code will not be deployed without resolving the errors at vscode however it's now deployed successfully.

**Comment by Himanshu-karnwal** [comment]
@rohitji95 - i'm unable to deploy my code to my scratch org. could you please help on this?

**Comment by rohitji95** [comment]
@Himanshu-karnwal I'm quite new to it but I would definitely try to figure out the issue here. What error you are facing. Pls make sure that you are logged in to the scratch org in vscode before performing the deployment.

**Comment by Himanshu-karnwal** [comment]
@rohitji95 thanks for the quick response. I figured it out. Actually we wont be able to deploy the code to the scratch org. As there is not deploy to scratch org functionaity. We need to Push it to the scratch org and which validate the code in the scratch and it fails due to the same error. So, i deploy to my dev org and not scratch org and it worked fine.

**Comment by midzelis** [comment]
A workaround is to turn off css validation for html files. Go to settings: Extensions: HTML: Validate: Styles: and turn off "Controls whether the built-in HTML language support validates embedded styles"

**Comment by allanmurimi** [comment]
> A workaround is to turn off css validation for html files. Go to settings: Extensions: HTML: Validate: Styles: and turn off "Controls whether the built-in HTML language support validates embedded styles"

this was very helpful...

**Comment by Hasara98** [comment]
.status{

    border-radius:0.5rem;
    background-color: rgb(219, 26, 177);
    padding: 0.2rem 1rem;
    text-align: center;

  
   &-pending{
        background-color: yellow;
    
    }
    &-cooking{
        background-color: hotpink;
    } 
}

error- } expectedcss(css-rcurlyexpected

**Comment by aygnsdqva** [comment]
Unfortunately , This doesn't solve my same problem
