### ISSUE TITLE
Recipe "compositionBasics" says it uses the api decorator but it does not.

### ISSUE THREAD

**Issue by ethanone1** [trailheadapps/lwc-recipes#123]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot or code snippets_.

**Comment by muenzpraeger** [comment]
It does [here](https://github.com/trailheadapps/lwc-recipes/blob/master/force-app/main/default/lwc/compositionBasics/compositionBasics.html#L4).
