### ISSUE TITLE
Passing attributes from Aura component to LWC

### ISSUE THREAD

**Issue by pmdartus** [trailheadapps/lwc-recipes#125]
Originally created by @briannabrownOE in https://github.com/salesforce/lwc/issues/1469

----

**Is your feature request related to a problem? Please describe.**
The auraEmbeddedLWC example from the `lwc-recipes` app provides a clear example for how to pass variables from a child LWC to a parent Aura cmp. However, I've found it difficult to find any examples of how to traverse the relationship from parent Aura cmp to child LWC. I was able to find a bit of a clue from the below note on the `auraPubsubPublisher.cmp` - but would still benefit from an example to clarify.

> Parent-to-child communication where the parent is an Aura component:
 >- If the child is an Aura component, use attribute passing or call an aura:method defined in the child component
 >- If the child is a Lightning Web component, use attribute passing or call a public @api method defined in the child component

**Describe the solution you'd like**
It would be great to include an example of how to pass an aura attribute to an embedded child lwc within the `lwc-recipes` repo. In a more immediate sense, if someone could help guide me a bit in how to do this, it would be much appreciated.

**Describe alternatives you've considered**
I've attempted to expose a variable in my lwc component with the `@api` decorator and then pass that variable value to a `@wire` call to a server side apex method:
```    
@api productServiceName;
@wire(getOptionalProds, {productServiceName: '$productServiceName'}) products;
```

In my aura cmp i'm setting an attribute value from a flow and then attempting to pass that value to the lwc child cmp:

```
<aura:component implements="lightning:availableForFlowScreens" access="global" controller="QuoteLineItemController">
<aura:attribute name="ProductServiceName" type="string"/>
<c:optionalQuoteLineItemDataTable product-service-name="{!v.ProductServiceName}" onproductidlist="{!c.receiveProductIds}"/>
```

Unfortunately, this isn't working and i've run out of ways of troubleshooting what is going wrong.

**Additional context**
I really appreciate the help!

**Comment by pmdartus** [comment]
I think renaming the attribute name from `product-service-name` to `productServiceName` in your aura component should solve the issue.

```
<c:optionalQuoteLineItemDataTable productServiceName="{!v.ProductServiceName}" onproductidlist="{!c.receiveProductIds}"/>
```

That being said it would be great to add an example where some properties are passed from Aura to LWC.

**Comment by muenzpraeger** [comment]
We have a couple of examples in the sample apps that contain this example.

I recommend to take a look at [this one](https://github.com/trailheadapps/purealoe-lwc/blob/master/force-app/main/default/aura/irrigationManagerWrapper/irrigationManagerWrapper.cmp#L26), where we do exactly that - embedding a Lightning web component in an Aura component that is part of a Flow.

**Comment by briannabrownOE** [comment]
Thanks for the help @pmdartus and @muenzpraeger with your tips I was able to get it working! Much appreciated 😄

**Comment by briannabrownOE** [comment]
@muenzpraeger I'm wondering if you have any similar examples/or suggestions for creating a toast message after data has been received by my parent aura component. I think i'm experiencing [this known issue](https://success.salesforce.com/issues_view?id=a1p3A000000mCRqQAM&title=lightning-component-force-showtoast-displays-toast-message-behind-action-window-in-lightning-experience-and-salesforce1) and was wondering if there are ways of getting around it.

On a click action i'm sending a list of ids --> aura cmp and from my aura cmp --> flow collection variable. Is it possible to chain a `ShowToastEvent` to the event below?
```
createQuoteLineItems(event) {
        const productIDs = productIDsForQuoteLineItemCreate;
        const sendDataToAura = new CustomEvent('productidlist', {
            detail: {productIDs},
        });
        this.dispatchEvent(sendDataToAura)
}
```

Once again any and all help is much appreciated!

**Comment by muenzpraeger** [comment]
IMHO there's no reason why you can't call it within `createQuoteLineItems`.
