### ISSUE TITLE
A lightning-input-field for a checkbox field in lightning-record-edit-form, the field can only be saved once.

### ISSUE THREAD

**Issue by all2human** [trailheadapps/lwc-recipes#131]
### Summary

When using lightning-input-field for a checkbox field in lightning-record-edit-form, the field can only be saved once.  Other fields can be changed and saved more than once. NOTE: a custom checkbox field on Contact was used in the testing.  

force-app/main/default/lwc/recordEditFormDynamicContact/recordEditFormDynamicContact.html

### Steps To Reproduce:

1.  Add a lightning-input-field for a checkbox field in lightning-record-edit-form for the above recordEditFormDynamicContact component.
2.  Test saving the contact record by changing the checkbox field and clicking the Save button.  Verify the results.  Change the field again, click the Save button and verify the field was not saved.

### Expected result

Checkbox lightning-input-field should save every time when saving the record.

### Actual result

Checkbox fields are NOT saved after the first time saving the record .

**Comment by muenzpraeger** [comment]
@all2human That sounds like an observation with a product implementation, and it's not related to this repo.

I suggest you post your question [here](https://salesforce.stackexchange.com/).
