### ISSUE TITLE
d3 library script and css is not loaded.

### ISSUE THREAD

**Issue by Sheing** [trailheadapps/lwc-recipes#14]
[d3 not loading correctly](https://i.imgur.com/WaBnBYU.png)

The real result should show this example I assume--> https://bl.ocks.org/mbostock/2675ff61ea5e063ede2b5d63c08020c7

Maybe it's not loading the script and css correctly.

**Comment by prem-pal** [comment]
It's loading for me. Can you provide some more details?

**Comment by Sheing** [comment]
Tried it in different browsers (Safari, Chrome and Firefox), checked the console log, nothing was throwing errors. The scripts showed up in the source. The promise callback is successful but nothing showed up. Current branch is on sync with the latest master branch.

**Comment by prem-pal** [comment]
Could you try installing the unlocked package, if not done already?

**Comment by Sheing** [comment]
Installed the unlocked package in Spring 19 Scratch org, still doesn't display anything. Only other thing i can think of is there's some insecure connection in that D3 library, which my sophos security blocked it.

**Comment by madjon** [comment]
I can also confirm that the D3.js chart did not show up for me.

**Comment by pmdartus** [comment]
@Sheing It's interesting, what version of Chrome are you running? What plugins are installed?

**Comment by Sheing** [comment]
@pmdartus I am using the latest chrome version Version 71.0.3578.98 (Official Build) (64-bit), tried it in Safari, Firefox and Edge, didn't work on those browsers either. I tried to disabled all my other extension, and that didn't resolve that issue too.

**Comment by rkathir** [comment]
I'm using Firefox, I could not get the LWC page working, it is a blank page with Hello icon in Hello Tab..

**Comment by muenzpraeger** [comment]
Fixed by #43
