### ISSUE TITLE
Add support for Apex formatting using Prettier

### ISSUE THREAD

**Issue by muenzpraeger** [trailheadapps/lwc-recipes#141]
**What is missing from the application? Please describe.**
The current project does not format Apex using [Prettier](https://prettier.io/).
    
**Describe the solution you'd like**
The [Apex Prettier Plugin](https://www.npmjs.com/package/prettier-plugin-apex) has to be implemented to format any Apex related file. That way it aligns with the formatting options in Developer Console.

**Comment by pchittum** [comment]
Fixed with PR https://github.com/trailheadapps/lwc-recipes/pull/167
