### ISSUE TITLE
Exclude temporary files from local-dev-server for git commits

### ISSUE THREAD

**Issue by muenzpraeger** [trailheadapps/lwc-recipes#142]
**What is missing from the application? Please describe.**
The newly introduced local development server for on-platform LWC creates a new local folder within DX projects. That folder holds temporary data.
    
**Describe the solution you'd like**
The folder should be excluded from `git` commits, as the data is only temporary. For that the `.gitignore` needs to be updated exactly as in [this pull request](https://github.com/trailheadapps/ebikes-lwc/pull/80).

**Comment by pchittum** [comment]
merge awaiting in pr 156 https://github.com/trailheadapps/lwc-recipes/pull/156

**Comment by pchittum** [comment]
Fixed with PR https://github.com/trailheadapps/lwc-recipes/pull/167
