### ISSUE TITLE
LWC Recipes components missing tests

### ISSUE THREAD

**Issue by cbjhnson** [trailheadapps/lwc-recipes#181]
### Summary

This customer-facing documentation says:
"Looking for More Examples? The lwc directory of our lwc-recipes repo has tests for every recipe. Each recipe has a __tests__ directory with commented jest tests."

Yet there are several lwc-recipes that don't have any tests or even a __tests__ folder. Here are some examples (not including all because some modules may not have tests by design):
- navToChatterHome
- navToFilesHome
- navToHelloTab
- navToHome
- navToListView
- navToRecord
- navToRelatedList

### Steps To Reproduce:

1.  Navigate to force-app/main/default/lwc/<anyRepoMentionedAbove>

### Expected result

There should be a tests in a __tests__ folder according to the documentation.

### Actual result

There isn't a __tests__ folder with tests.

**Comment by pchittum** [comment]
PR merged into Master. Thanks for helping us make the sample apps better!
