### ISSUE TITLE
LWC1518: Invalid LWC imported identifier "getComponentDef"

### ISSUE THREAD

**Issue by juvian** [trailheadapps/lwc-recipes#182]
I have a regular developer org, with lightning experience enabled. I am using lwc components to use with lightning out in visualforce. I am not being able to deploy a component using import {getComponentDef} from 'lwc';

If I check the loaded aura_prod.js in salesforce, it does export getComponentDef. Is a scratch org the only way to fix this? 

Is there any workaround to set the getComponentDef function as a global property in window and call that in the component? I don't need it to work in lightning experience, only in visualforce.

**Comment by pchittum** [comment]
@juvian this seems like a general question on LWC and maybe related to this SF Stack Exchange post: https://salesforce.stackexchange.com/questions/288034/how-to-extend-a-sf-lightning-web-component/288307#288307

If so, I'll close this, and either answer or find someone to answer your question on SFSE.

**Comment by juvian** [comment]
@pchittum yeah that's my own question and finally found myself the answer which was using getComponentDef. But the issue is that does not work with lightning out, even when it does work outside salesforce
