### ISSUE TITLE
Error Testing Imperative Apex Calls

### ISSUE THREAD

**Issue by AllanOricil** [trailheadapps/lwc-recipes#183]
### Summary

We are testing an apex method that is called imperatively in the lwc. We followed this [recipe](https://github.com/trailheadapps/lwc-recipes/blob/master/force-app/main/default/lwc/apexImperativeMethod/__tests__/apexImperativeMethod.test.js).
The only difference is that our apex method is called in the Connected Calback because we need the data right away before calling an API in the client side using just javascript. The component works fine and it does everything it was suppose to do. The problem starts when testing it with jest.

There are two jest tests that are using the mocking method "getUserAndCustomMetadataProperties". The values that this method return are used in  a wired method that the "topResolutionsListAdapter" is adapting. The second test method fails whenever the first test method is in the code. If I comment the first test method, the second test method passes. 
My conclusion is that the getUserAndCustomMetadataProperties is not working twice in a row with the same response, since when there are two test methods using it, the second one does not work. 
After each test we are also cleaning everything.

```javascript
it('Test that Loading Spinners appear when there is no Data', () => {
        fetch = global.fetch = mockFetch(apiResponse.multipleProducts, apiResponse.multipleOids);
        
        getUserAndCustomMetadataProperties.mockResolvedValue(APEX_USER_AND_CUSTOM_METADATA_PROPERTIES_SUCCESS);
        
        const element = createElement('c-topResolutions-component', {
            is: GsdCepTopResolutions,
        });
        document.body.appendChild(element);
        
        const spinners = element.shadowRoot.querySelectorAll('lightning-spinner');
        expect(spinners.length).toBe(2);
        for(let i = 0; i < spinners.length; i++){
            expect(spinners[i].size).toEqual('small');
            expect(spinners[i].variant).toEqual('brand');
        }
    });

    it('Test How Top Resolutions Wire Method Uses the Dynamic Product Oids', () => {
        fetch = global.fetch = mockFetch(apiResponse.multipleProducts, apiResponse.multipleOids);

        getUserAndCustomMetadataProperties.mockResolvedValue(APEX_USER_AND_CUSTOM_METADATA_PROPERTIES_SUCCESS);

        const element = createElement('c-topResolutions-component', {
            is: GsdCepTopResolutions,
        });
        document.body.appendChild(element);
        topResolutionsListAdapter.emit(mockTopResolutionstList);
        securityBulletinsListAdapter.emit(mockSecurityBulletinsList);
        
        return flushPromises().then(() => {
            expect(topResolutionsListAdapter.getLastConfig()).toEqual(
                { productOids: '465619,465674,465616', toggleOids: false, activeTabTitle: "Top Resolutions" }
            );
        });
    });
```

Method to execute after each Test

```javascript
afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
        jest.clearAllMocks();
    });
```

Just to summarize again. If I comment the first test method, the second test method works fine!

**Comment by kerbelda** [comment]
Could you share your solution?

**Comment by AllanOricil** [comment]
> Could you share your solution?

@kerbelda I don't remember. But I think It was related to not call `jest.clearAllMocks();` after each test.
