### ISSUE TITLE
Cannot execute task prettier

### ISSUE THREAD

**Issue by gatormike** [trailheadapps/lwc-recipes#184]
I'm getting the following error trying to run prettier via `npm run prettier` on Win10, as per the [ReadME.md](https://github.com/trailheadapps/lwc-recipes/blob/master/README.md).  Here is the output from VS Code but I also tried PS.

> Executing task: npm run prettier <
> 
> lwc-recipes@0.1.0 prettier D:\Development\lwc-recipes
> prettier --write '**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,yaml,yml}'
> 
> [error] No matching files. Patterns tried: '**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,yaml,yml}' !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! lwc-recipes@0.1.0 prettier: `prettier --write '**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,yaml,yml}'`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the lwc-recipes@0.1.0 prettier script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Mike\AppData\Roaming\npm-cache\_logs\2019-12-30T03_56_05_066Z-debug.log
> The terminal process terminated with exit code: 1
> 
> Terminal will be reused by tasks, press any key to close it.

**Comment by pchittum** [comment]
Thanks for submitting this @gatormike.

**Comment by pchittum** [comment]
PR merged into Master. Closing this issue.
