### ISSUE TITLE
Modal recipe doesn't fade in

### ISSUE THREAD

**Issue by AndrewRayCode** [trailheadapps/lwc-recipes#190]
### Summary

The modal recipe does not fade in

### Steps To Reproduce:

1. Implement the modal recipe

### Expected result

The modal fades in

### Actual result

The modal does not fade in

### Additional information

It seems like the thing that causes a modal to fade in is the _toggling_ of the class "slds-fade-in-open". However with the recipe the class is hard coded onto the modal, and wraps the whole thing in a `<template if:true>`, so the whole thing is shown instantly and the class isn't toggled.

The modal recipe has several issues (at least one of which is because of the LWC framework in general) making it a little scary to use in a real app, but I think this one is addressable with some creative coding

Edit: Same for the backdrop, looks like

**Comment by pchittum** [comment]
Thanks! We'll look into revising this recipe in the future.

**Comment by AndrewRayCode** [comment]
More generally, the modal doesn't do most of the things that the SLDS design system require https://www.lightningdesignsystem.com/components/modals/ especially accessibility
