### ISSUE TITLE
Cannot call overloaded methods in Apex using Wire method

### ISSUE THREAD

**Issue by Daniel-Deepak-Dev** [trailheadapps/lwc-recipes#196]
### Summary

Apex and Java can overload methods which is not supported in javascript. So while wiring a method in apex which has two methods with same name and parameter counts are different. Wire is only calling the method with more number of parameter currently. 

### Steps To Reproduce:

1.  Create a apex class with two methods with same name and different number of parameter count. for example.
```
public with sharing class ApexClass {
    @AuraEnabled(cacheable = true) 
    public static string apexMethod(Integer x) {
        return 'returned one param apex method';
    }
    @AuraEnabled(cacheable = true) 
    public static string apexMethod(Integer x, Integer y) {
        return 'returned two param apex method';
    }
}
```
2.  Try to call the apexMethod with single param in Javascript
```
import { LightningElement, wire, track } from "lwc";
import apexMethod from "@salesforce/apex/apexLwc.apexMethod";


export default class TestLwc extends LightningElement {
  @track count;
  
  @wire(apexMethod, {x: "$count"})
     wireApexMethod({ error, data }) {
         //data = 'returned two param apex method' 
         //error = undefined
     }
  handleChange(e) {
    this.count = e.target.value;
  }
}
```

### Expected result

_The expected result should be `//data = 'returned one param apex method'`  in my opinion_.

### Actual result

`//data = 'returned two param apex method'` This should be the result since I am providing only one parameter value.

### Additional information

_Wire Method is also triggering if I am providing incorrect parameter variable name in javascript_

**Comment by muenzpraeger** [comment]
You can't overload. It's specified in the ["Wire an Apex Method to a Property" section of the documentatiuon](https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.apex), where `apexMethodParams` is described.

**Comment by Daniel-Deepak-Dev** [comment]
I am sorry, I haven't read the point. Thank you.
