### ISSUE TITLE
Remove setter and getter from CustomWrapper apex class as part of Spring 20 update

### ISSUE THREAD

**Issue by pranayjswl007** [trailheadapps/lwc-recipes#198]
**What is missing from the application? Please describe.**
CustomWrapper apex class has setter and getter for every variable, to make apex values readable in LWC JS. Prior to Spring 20, without setter getter the values are not visible, but now with Spring 20 they are. Thus we should update LWC recipie to reflect same.

**Describe the solution you'd like**
Remove setter and getter from `CustomWrapper.apex`. 
More info : https://salesforce.stackexchange.com/a/292185/19118

**Describe alternatives you've considered**

**Additional context**

**Comment by jbleyleSF** [comment]
@pranayjswl007 Is this Apex change documented in the Salesforce Release Notes? I can't find it. TIA
http://releasenotes.docs.salesforce.com/en-us/spring20/release-notes/rn_apex.htm?edition=&impact=

**Comment by pchittum** [comment]
@pranayjswl007 we'll look into this for our upcoming update cycle.

**Comment by pchittum** [comment]
@pranayjswl007, despite the answers and comments on the linked SFSE answer, I've tested every combination of switching property syntax to Apex attributes, and in each case, any Apex wrapper class members declared as public attributes get instantiated as `null`. But when restoring the property syntax, it works again. 

I even tried testing in a separate stand-alone project. Even with a simple wrapper class with one property and two attributes, the attributes fail, while the property works. 

see here: https://github.com/pchittum/test-custom-apex-types-and-lwc

**Comment by muenzpraeger** [comment]
Is this still relevant, @pchittum?

**Comment by pchittum** [comment]
Currently an `@AuraEnabled` attribute functions as a _return type_. However using complex object _input_ to an Apex method requires that the custom Apex type use the property syntax. 

Here's an example of the working return type. 

Ideally this would be consistent behavior on input or return, so I'm going to take this to product and close this issue. 

Return types as custom apex classes is a pretty common pattern. We should evaluate adding a recipe with that, or updating the existing recipe to show both.
