### ISSUE TITLE
Replace for loop construction of array to map() function. 

### ISSUE THREAD

**Issue by pchittum** [trailheadapps/lwc-recipes#224]
**What is missing from the application? Please describe.**
The `apexWireMethodWithComplexParams` code in the `handleListItemChange` function uses a `for(...)` loop to construct an array of arbitrary length. In general higher order functions are a preferred practice. 

**Describe the solution you'd like**
We can use something like the following as a replacement of the for loop. 
```js
    handleListItemChange(event) {
        const someList = [...Array(event.target.value)].map( () => {
                someInnerString: this.stringValue,
                someInnerInteger: this.numberValue
            })
    ...
```

**Comment by kevinv11n** [comment]
Array.map returns a new array so there's no need to destructure it, which creates an extra array. 

```js
    handleListItemChange(event) {
        const someList = Array(event.target.value).map( () => {
            someInnerString: this.stringValue,
            someInnerInteger: this.numberValue
        })
    ...
```

**Comment by pchittum** [comment]
Calling `Array(event.target.value)` creates an array with a length, but no elements for `Array.map` to iterate over. For instance. 

```js 
const arr1 = Array(50).map( ()=> 'some value' ); 
console.log(arr1.length); // 50
console.log(arr1[0]); // undefined
```

Using spread forces the elements to materialize so that you can then call `map` on them and then populate them accordingly. 

```js 
const arr1 = [...Array(50)].map( ()=> 'some value' ); 
console.log(arr1.length); // 50
console.log(arr2[0]); // "some value"
```

To be fair, I didn't figure this out, rather was reading about it. But this begs the question: is it worth creating the extra array (as you point out @kevinv11n) just to use `map` to populate this list? Especially if just using the `for` loop doesn't incur the cost of an additional array? 

I find myself wanting to show the higher order function, to have the example for our developers. But I'll admit, it's a bit of an obscure use of `Array.prototype.map` and (outside of learning how `Array()` works) may not have a lot of other applications in the real world. Interested in your thoughts.
