### ISSUE TITLE
AuraPubsub improvement

### ISSUE THREAD

**Issue by antonyxuan** [trailheadapps/lwc-recipes#225]
**What is missing from the application? Please describe.**
There is currently an issue when we using auraPubsub for me don't know if anyone else have similar issue. 
The error occurred randomly because aura component is complete on rendering auraPubsub LWC then I have onready event handler to registerListener, but for half of time I have the wired pageRef variable still undefined, which will future get an exception from pubsub.js.

**Describe the solution you'd like**
I have following solution which need a touch on auraPubsub.js don't know if that can help with above issue or not.

    retryAddListener;
    pageRef;

    @wire(CurrentPageReference) wiredPageRef(pageRef) {
        this.pageRef = pageRef;
        if (this.retryAddListener) {
            this.registerListener(this.retryAddListener.eventName, this.retryAddListener.callback);
        }
    }

    connectedCallback() {
        this.dispatchEvent(new CustomEvent('ready'));
    }

    @api
    registerListener(eventName, callback) {
        if (!this.pageRef) {
            this.retryAddListener = {
                eventName: eventName,
                callback: callback
            };
        } else {
            registerListener(eventName, callback, this);
        }
    }

**Describe alternatives you've considered**
I had a through on changing pubsub.js, but I think that will be little bit risky

**Additional context**

![Screen Shot 2020-02-20 at 3 40 38 pm](https://user-images.githubusercontent.com/7123658/74901600-7436d700-53f7-11ea-8f2b-d0128d286914.png)

**Comment by pchittum** [comment]
Thanks for posting this. We'll look into this more closely next week.

**Comment by pchittum** [comment]
FYI, @antonyxuan if you look in the `beta` [branch](https://github.com/trailheadapps/lwc-recipes/tree/beta), you'll start to see things are being added to show Lightning Message Service.

**Comment by antonyxuan** [comment]
Thanks @pchittum that make sense, Lightning Message Service should eventually replace pubsub.

**Comment by pchittum** [comment]
I'm closing this. With the roll out of LMS, we'll be removing pub sub from the examples in this app.
