### ISSUE TITLE
Found 2 vulnerabilities (1 moderate, 1 high) error during `npm install`

### ISSUE THREAD

**Issue by hemendrarajawat** [trailheadapps/lwc-recipes#226]
### Summary
Getting "**found 2 vulnerabilities (1 moderate, 1 high**)" error while running `npm install` command.

### Steps To Reproduce:
1. Clone the "lwc-recipes" into the local system
1. Open the cmd in the "lwc-recpies" folder and run `npm install` command
1. After some time it gives this error:

> found 2 vulnerabilities (1 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

### Expected result
`npm install` command should be completed without any error

### Actual result
Receiving error

### Additional information
```
>npm audit

                       === npm audit security report ===


                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance


  Moderate        Denial of Service

  Package         js-yaml

  Patched in      >=3.13.0

  Dependency of   @salesforce/sfdx-lwc-jest [dev]

  Path            @salesforce/sfdx-lwc-jest > @lwc/compiler >
                  @lwc/style-compiler > cssnano > postcss-svgo > svgo >
                  js-yaml

  More info       https://npmjs.com/advisories/788


  High            Code Injection

  Package         js-yaml

  Patched in      >=3.13.1

  Dependency of   @salesforce/sfdx-lwc-jest [dev]

  Path            @salesforce/sfdx-lwc-jest > @lwc/compiler >
                  @lwc/style-compiler > cssnano > postcss-svgo > svgo >
                  js-yaml

  More info       https://npmjs.com/advisories/813

found 2 vulnerabilities (1 moderate, 1 high) in 896259 scanned packages
  2 vulnerabilities require manual review. See the full report for details.
```

**Comment by pchittum** [comment]
Thanks for raising this.

**Comment by pozil** [comment]
Hi @hemendrarajawat, these two security issues are coming from `js-yaml` a dependency of `@salesforce/sfdx-lwc-jest`. We're already on latest version `@salesforce/sfdx-lwc-jest` so we have to wait for an update.

In the meantime, rest assured, there's no risk because `@salesforce/sfdx-lwc-jest` is a development dependency: it’s not shipped to production, it’s only used locally when running tests.
