### ISSUE TITLE
LibsChartJS example doesn't work

### ISSUE THREAD

**Issue by KarenVelasco** [trailheadapps/lwc-recipes#227]
It was working but on February 21st it stopped and we're getting this error:

TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at DocumentFragment.value [as appendChild] (aura_prod.js:1)

**Comment by pchittum** [comment]
Thanks, @KarenVelasco. Can you provide any further details about this? I'm looking at a scratch org I just stood up with the chartJS recipe from the Spring 20 `master` branch. It's working fine. 

If you run `npm install` and then run `npm run test:unit` do all tests pass? 

Also, any details on things like browser you're using, etc. would be helpful. 

And are there any details or errors in the console if you open up dev tools in your browser?

**Comment by KarenVelasco** [comment]
Hello!

There was a problem with my ChartJS file as static resource. I uploaded it again and now it works. 

Thanks!
