### ISSUE TITLE
lightning-formatted-number Currency Issue

### ISSUE THREAD

**Issue by rtotla83** [trailheadapps/lwc-recipes#229]
While using <lightning-formatted-number> I am not able to format it as ##.###.##0,00
I cannot pass this value in the attribute format-style.

It will impact currency value in Europe region & not display in specific format.

**Comment by pchittum** [comment]
@rtotla83 This repo and issues here are only for fixing the actual recipes and examples we've implemented. I think this may be a question more about the behavior of the `lightning-formatted-number` component, right? 

If you have a question about that, post it on the Salesforce [StackExchange](https://salesforce.stackexchange.com/questions/tagged/lightning-web-components) and tag it with lightning-web-components. The product team tracks things there.

**Comment by pchittum** [comment]
@rtotla83, I've raised this concern to the base components team internally. I'd still suggest you add a question to StackExchange for greater visibility. 

If you need to have localised number punctuation, for the time being, I'd probably suggest foregoing the `<lightning-formatted-number>` tag, and make use of the standard `Intl.NumberFormat` js [api](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) in the js file of the component you're using. 

For now, I'm going to close this issue. Thanks!

**Comment by sfdciuie** [comment]
@rtotla83 See https://developer.salesforce.com/docs/component-library/bundle/lightning-formatted-number/documentation

Specifically:

> A lightning-formatted-number component displays formatted numbers for decimals, currency, and percentages. Use format-style to specify the number style. This component uses the Intl.NumberFormat JavaScript object to format numerical values. **The locale set in your Salesforce user preferences determines how numbers are formatted**.

**Comment by rtotla83** [comment]
Thanks Luri,
But the thing is that it is not working in LWC community.
It works fine when you pass currency and code on playground but when I
tried same thing and render it in community it fails to load the format.
Also the user locale is set as Sweden.

I also change my system locale to Europe but no success.

Please let me know if any work around is there

Regards
Rohit

**Comment by sfdciuie** [comment]
@rtotla83 I would suggest you reach out to salesforce support, they should be able to help you out, alternatively as @pchittum mentioned you can use Intl.NumberFormat directly
