### ISSUE TITLE
Fix lint-staged commit warning

### ISSUE THREAD

**Issue by pozil** [trailheadapps/lwc-recipes#237]
Problem: each commit to the project outputs this warning:
`⚠ Some of your tasks use `git add` command. Please remove it from the config since all modifications made by tasks will be automatically added to the git commit index.`

Fix: Current version of `lint-staged` automates `git add` action so we need to remove this from `package.json`:
```json
"*": [
  "git add"
]
```

**Comment by muenzpraeger** [comment]
@pchittum

**Comment by PLQin** [comment]
nice ， solved my problem！
