### ISSUE TITLE
Error-panel doesn't follow SLDS UX

### ISSUE THREAD

**Issue by albarivas** [trailheadapps/lwc-recipes#247]
Hi team. The error-panel component in lwc-recipes doesn’t follow our own UX guidelines. What the UX team suggests to do is something like this: https://www.lightningdesignsystem.com/guidelines/empty-state/.

**Comment by muenzpraeger** [comment]
The panel is used across all sample apps. Please make an implementation suggestion, which then can be replicated, with the same functionality as the current panel. TY!

**Comment by muenzpraeger** [comment]
Bumping this up @albarivas in your inbox. ;-)

**Comment by albarivas** [comment]
Fixed on PR https://github.com/trailheadapps/lwc-recipes/pull/260
