### ISSUE TITLE
Picture__c does not exist for Contact, on force:source:push

### ISSUE THREAD

**Issue by annyhe** [trailheadapps/lwc-recipes#27]
In ContactController.cls the file calls for Picture__c. But there is no Picture__c field in scratch orgs.
Pushing to scratch org fails with

sfdx force:source:push
PROJECT PATH                                          ERROR
────────────────────────────────────────────────────  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
force-app/main/default/classes/ContactController.cls  Id, Name, Title, Phone, Email, Picture__c FROM Contact WHERE Picture__c
                                                                                     ^
                                                      ERROR at Row:1:Column:39
                                                      No such column 'Picture__c' on entity 'Contact'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names. (5:16)
force-app/main/default/classes/ContactController.cls  Id, Name, Title, Phone, Email, Picture__c FROM Contact WHERE Name
                                                                                     ^
                                                      ERROR at Row:1:Column:39
                                                      No such column 'Picture__c' on entity 'Contact'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names. (11:16)
force-app/main/default/classes/ContactController.cls  Id, Name, Title, Phone, Email, Picture__c FROM Contact LIMIT 1
                                                                                     ^
                                                      ERROR at Row:1:Column:39
                                                      No such column 'Picture__c' on entity 'Contact'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names. (16:16)
16:18:16.603 sfdx force:source:push ended with exit code 1

**Comment by muenzpraeger** [comment]
Have you tried with another scratch org? The mentioned field is part of the projects metadata.

https://github.com/trailheadapps/lwc-recipes/blob/master/force-app/main/default/objects/Contact/fields/Picture__c.field-meta.xml

**Comment by joshua-nicholson** [comment]
This is old, but for anyone else running in this you probably forgot to apply the permission set to your user.

`sfdx force:user:permset:assign -n recipes`
