### ISSUE TITLE
Modal "Cancel" or "Close" Buttons Raise Error

### ISSUE THREAD

**Issue by MWF-Salesforce-Developer** [trailheadapps/lwc-recipes#282]
### Summary

After installing the Modal, ViewSource, and MiscModal LWCs, clicking the "Cancel" or "Close" buttons on the modal result in an error stating " [Cannot read property 'classList' of null]", stack trace "d.handleSlotFooterChange()@https://my-org.lightning.force.com/lightning/n/modules/c/modal.js:4:2436". This happens every time the modal is opened and then re-closed, using either the "Cancel" or "Close" buttons.

### Steps To Reproduce:

1.  Save the Modal, ViewSource, and MiscModal LWC's to your org from lwc-recipes.
2.  Display the MiscModal component and click the "Show Modal" button
3.  Click either the "Cancel" or "Close" buttons 

### Expected result

The modal should close without error.

### Actual result

The modal.handleSlotFooterChange() method throws error "[Cannot read property 'classList' of null]".

### Additional information

![image](https://user-images.githubusercontent.com/45638903/81732590-8ac45b80-9445-11ea-85d8-5d5622b8b3fc.png)

All code being used as been copied and pasted from the lwc-recipes for Modal, ViewSource, and MiscModal.

Additional information can be provided upon request.

**Comment by satyasekharcvb** [comment]
Hi @MWF-Salesforce-Developer, I tried to reproduce this issue multiple times but it is working as expected.

Can you please try deploying it in a new scratch org?

Thanks!

**Comment by carlhussey-asu** [comment]
Experiencing this same issue.

* Open Modal fires the `onslotchange` when it shows the button.
* Clicking close/cancel calls `modal.hide(); `
* This makes `<template if:true={showModal}> = false` and hides it from the DOM
* `Onslotchange` fires again looking for `this.template.querySelector("footer”);` which no longer exists  which results in `footerEl.classList` returning null
