### ISSUE TITLE
Rendering components dynamically

### ISSUE THREAD

**Issue by narendrasinghrathore** [trailheadapps/lwc-recipes#283]
```
import ComponentA from 'c/componentA';
import ComponentB from 'c/componentB';
import ComponentC from 'c/componentC';
import ComponentD from 'c/componentD';

list = [
 { title:'A', component: ComponentA },
 { title:'B', component: ComponentB },
 { title:'C', component: ComponentC },
 { title:'D', component: ComponentD },
];
```

```
<template for:each={list} for:item='item'>
	{item.component}
</template>
```

Is there possible way to implement this, what i see from documentation we can use render method which only render one component at a time.

**In my case, each component would have their own implementation (for.eg Profile, Setting ,etc Components ).
Now you have a  parent component which is tab container and we iterate a list from which we load components dynamically using iterator or for:each  as separate tab under parent tab container.**

```
render() {
        return this.showTemplateOne ? templateOne : templateTwo;
}
```

**Comment by ashish-garg07** [comment]
You can create two HTML page and from the render method, you will return which page you want to show.

**Comment by narendrasinghrathore** [comment]
> You can create two HTML page and from the render method, you will return which page you want to show.

Can you please share some working code link?

**Comment by muenzpraeger** [comment]
See [here](https://github.com/trailheadapps/lwc-recipes/tree/master/force-app/main/default/lwc/miscMultipleTemplates).

**Comment by narendrasinghrathore** [comment]
> See [here](https://github.com/trailheadapps/lwc-recipes/tree/master/force-app/main/default/lwc/miscMultipleTemplates).
In the example you can either use one of them but in my case I need to render both templates same time and using foeach.

**Comment by muenzpraeger** [comment]
That's not possible.

**Comment by joeythomaschaske** [comment]
Would this be possible today with dynamic imports?
