### ISSUE TITLE
Add CORS handling to MiscRestApiCall

### ISSUE THREAD

**Issue by rrcook** [trailheadapps/lwc-recipes#316]
**What is missing from the application? Please describe.**
 I'd like to see an implementation of MiscRestApiCall that handles sites that use CORS. The googleapi call works, but when going to many other sites I get an error such as
Access to fetch at 'https://www.metaweather.com/api/location/search/?lattlong=35.0526,-83.1968' from origin 'https://(mydevorg).lightning.force.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Describe the solution you'd like**
Clearer instructions on how to set up in Salesforce, or if necessary a proxy solution through Salesforce, for example an Apex class if that is the best way to handle it.
**Describe alternatives you've considered**
A workaround for the time being is to use this external proxy but it would be better to have a totally internal solution:
https://cors-anywhere.herokuapp.com/https://www.metaweather.com/api/location/search/?lattlong=35.0526,-83.1968

**Comment by pchittum** [comment]
Hi @rrcook. We'll discuss this internally. This could possibly be a new recipe. Alternately, I could see incorporating this into another sample app in a more "real life" use case.

**Comment by pchittum** [comment]
@rrcook, I've added this to our internal backlog to create a code sample and some content around dealing with CORS when using fetch directly from LWC. We think it would fit better in another sample app as a more "true to life" example, rather than a recipe here. 

Thanks again for this suggestion!
