### ISSUE TITLE
Audit and fix any components that perform direct assignment to a property instead of a getter

### ISSUE THREAD

**Issue by pchittum** [trailheadapps/lwc-recipes#323]
Component properties should not pass through a direct assigned value. Better is to wrap them in a getter. 

The component (`miscGetUserId`)[https://github.com/trailheadapps/lwc-recipes/blob/master/force-app/main/default/lwc/miscGetUserId/miscGetUserId.js] we direct assign the user Id value from `@salesforce/user/Id` to a property. 

This issue it to fix the `miscGetUserId` component and find and address any other offending direct-assigned properties and evaluate whether they should actually be implemented as getter/setters. For more details see #322.

**Comment by muenzpraeger** [comment]
`miscGetUserId` is fine to be directly assigned. See also the documentation [here](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.get_current_user).

**Comment by pchittum** [comment]
> `miscGetUserId` is fine to be directly assigned. See also the documentation [here](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.get_current_user).

"...fine to be directly assigned" seems pretty arbitrary if you compare between #322 and this, @muenzpraeger. If we're going to be opinionated about getter versus pass through, we should be consistent with ourselves, and not necessarily just because the docs do it that way. And if it isn't arbitrary, what's the separating line between when to opt for pass through and when to use a getter?
