### ISSUE TITLE
Incorrect icon for MiscRestApiCall

### ISSUE THREAD

**Issue by albarivas** [trailheadapps/lwc-recipes#328]
The MiscRestApiCall icon is different from the other Misc recipes:

![Screenshot 2020-07-14 at 12 56 03](https://user-images.githubusercontent.com/12017842/87418117-7e898580-c5d1-11ea-847d-f395413919e8.png)

**Comment by pchittum** [comment]
I always assumed that was intentional, "misc" being "misc" after all. The component for permission-based UI will also be a different icon.

**Comment by pchittum** [comment]
I'm going with WAD. We can take discussion offline if components on the Misc page should be all the same, or reflect their purpose/function.
