### ISSUE TITLE
Error installing the unlocked package on pre-release dev org

### ISSUE THREAD

**Issue by putskiz** [trailheadapps/lwc-recipes#35]
Your request to install package "LWCRecipes Spring '19" was unsuccessful. None of the data or setup information in your salesforce.com organization was affected.

If your install continues to fail, contact Salesforce CRM Support through your normal channels and provide the following information.

Organization: 4C (00DB0000000TfwR)
User: Emilien Guichard (005B0000005BoIf)
Package: LWCRecipes (04tB0000000cPFa)
Error Number: 1511090473-25288 (-644971859)
Problem:

1. (Apex) The c:apexWireMethodToProperty component must be marked 'isExposed=true' to be used on this Lightning Page
Apex: The c:apexWireMethodToProperty component must be marked 'isExposed=true' to be used on this Lightning Page

2. (Aura_Interoperability) The c:pubsubContactList component must be marked 'isExposed=true' to be used on this Lightning Page
Aura_Interoperability: The c:pubsubContactList component must be marked 'isExposed=true' to be used on this Lightning Page

3. (Composition) The c:compositionBasics component must be marked 'isExposed=true' to be used on this Lightning Page
Composition: The c:compositionBasics component must be marked 'isExposed=true' to be used on this Lightning Page

4. (Contact_Record_Page) The c:recordFormDynamicContact component must be marked 'isExposed=true' to be used on this Lightning Page
Contact_Record_Page: The c:recordFormDynamicContact component must be marked 'isExposed=true' to be used on this Lightning Page

5. (Data_Service) The c:lds component must be marked 'isExposed=true' to be used on this Lightning Page
Data_Service: The c:lds component must be marked 'isExposed=true' to be used on this Lightning Page

6. (Events) The c:eventSimple component must be marked 'isExposed=true' to be used on this Lightning Page
Events: The c:eventSimple component must be marked 'isExposed=true' to be used on this Lightning Page

7. (Hello) The c:hello component must be marked 'isExposed=true' to be used on this Lightning Page
Hello: The c:hello component must be marked 'isExposed=true' to be used on this Lightning Page

8. (Misc_Techniques) The c:miscGetUserId component must be marked 'isExposed=true' to be used on this Lightning Page
Misc_Techniques: The c:miscGetUserId component must be marked 'isExposed=true' to be used on this Lightning Page

9. (Navigation) The c:navToHome component must be marked 'isExposed=true' to be used on this Lightning Page
Navigation: The c:navToHome component must be marked 'isExposed=true' to be used on this Lightning Page

10. (Parent_to_Child) The c:apiProperty component must be marked 'isExposed=true' to be used on this Lightning Page
Parent_to_Child: The c:apiProperty component must be marked 'isExposed=true' to be used on this Lightning Page

11. (Pub_Sub) The c:pubsubSearchBar component must be marked 'isExposed=true' to be used on this Lightning Page
Pub_Sub: The c:pubsubSearchBar component must be marked 'isExposed=true' to be used on this Lightning Page

12. (Wire) The c:apexWireMethodToProperty component must be marked 'isExposed=true' to be used on this Lightning Page
Wire: The c:apexWireMethodToProperty component must be marked 'isExposed=true' to be used on this Lightning Page

13. (X3rd_Party_Libs) The c:libsD3 component must be marked 'isExposed=true' to be used on this Lightning Page
X3rd_Party_Libs: The c:libsD3 component must be marked 'isExposed=true' to be used on this Lightning Page

**Comment by muenzpraeger** [comment]
We released a new package version on Wednesday that fixed this.

https://github.com/trailheadapps/lwc-recipes/pull/36

**Comment by kccrs** [comment]
Your request to install package "LWCRecipes Spring '19" was unsuccessful. None of the data or setup information in your salesforce.com organization was affected.

Package: LWCRecipes (04tB0000000YGYO)
Error Number: 1911984685-17123 (-938529298)
Problem:

1. (recipes) In field: field - no CustomField named Contact.CleanStatus found
recipes: In field: field - no CustomField named Contact.CleanStatus found
