### ISSUE TITLE
Update README.md file: Make "Installing the app using an Unlocked Package" instructions more comprehensive

### ISSUE THREAD

**Issue by lmontero1114** [trailheadapps/lwc-recipes#352]
**What is missing from the application? Please describe.**
The "Installing the app using an Unlocked Package" section in the README.md file is missing instructions of assigning the permission sets to the users. This is being used in this [badge](https://trailhead.salesforce.com/content/learn/projects/quick-start-lwc-recipes-app) and it might be confusing for trailblazers not having the instructions there.

**Describe the solution you'd like**
I would like to see clear instructions of assigning the permission set to the users under the "Installing the app using an Unlocked Package" section in the README.md file.

**Comment by rsikhakolli** [comment]
After installing the Package by following the steps mentioned under the section "Installing the app using an Unlocked Package", the challenge is throwing an error as **We can't find the 'recipes' permission set assigned to your user.** And upon adding the permission set to the user, the challenge verifying successfully.

<img width="996" alt="Permissionset error" src="https://user-images.githubusercontent.com/61190344/89196092-5c2eca80-d5c7-11ea-9b47-79592de655b8.png">

So, please add the permission set assignment steps in the "Installing the app using an Unlocked Package" section. 
Thank you!

**Comment by pchittum** [comment]
Thanks for raising this issue @lmontero1114 and @rsikhakolli. We're discussing internally. 

I think short term, you're right that we can add an instruction, even though functionally it is extraneous, it is necessary to complete the hands-on challenge as currently defined. 

Long term, we're looking at a better option, like automatically assigning the permset in the case of app installation by package. 

Stay tuned!

**Comment by pchittum** [comment]
These instructions have been added to all the sample app repos where it's relevant. Thanks for bringing this to our attention and making the experience of the sample apps better for everyone.
