### ISSUE TITLE
Failed to deploy source and install package on new Winter '21 scratch orgs

### ISSUE THREAD

**Issue by mseneshen** [trailheadapps/lwc-recipes#361]
### Summary

The LWCRecipes package has failed to install on three out of four new scratch orgs that I've made today.

It appears the failed scratch orgs are all running the Winter '21 release:
![Image from Gyazo](https://i.gyazo.com/f85d198a878b5e4ffea8358621112e38.gif)

### Steps To Reproduce:

1.  Clone this repository
1.  Follow the steps in the README to create a scratch org.
1.  Check that the scratch org's release is Winter '21. 
1.  Deploy the source OR attempt to install the package.

### Expected result

The deploy or package install should succeed with no error.

### Actual result

<details>
  <summary>Deploying from source</summary>

```
=== Push Errors
PROJECT PATH                                                      ERRORS                                                                                       
────────────────────────────────────────────────────────────────  ─────────────────────────────────────────────────────────────────────────────────────────────
force-app\main\default\flexipages\Composition.flexipage-meta.xml  We couldn't retrieve the design time component information for component c:compositionBasics.
```

</details>

<details>
  <summary>Installing the package</summary>

[![Image from Gyazo](https://i.gyazo.com/8beea50e041969a73ab6a02372e0a2a6.png)](https://gyazo.com/8beea50e041969a73ab6a02372e0a2a6)

</details>

### Additional information

I didn't specify any specific release when I created the scratch org.

Interestingly, it seems that Winter '21 should not be available for preview until September 11 [according to this documentation](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_version_selection.htm), so I'm not sure why some of my scratch orgs are Winter '21.

I think it would be good to either make this package compatible with Winter '21 or add a notice to the README to ensure the scratch org is running Summer '20.

**Comment by pchittum** [comment]
Hi @mseneshen. As you noted, the packages that we create (and our packaging org) are always for the current major release, and we believe this is the best path forward, rather than having separate packaging during the pre-release cycle. 

We'll add the advisory. 

Thanks for helping us improve the sample apps!

**Comment by pchittum** [comment]
Quick update. This appears to have been an early problem in the new Winter 21 major release cycle. Normally a package in an older version can be installed in an org of a more recent release. 

I've verified today that I'm able to install in a scratch org on Winter 21. 

Thanks again for notifying us of this problem. If you find you're still having problems, please get back in touch. Cheers.
