### ISSUE TITLE
Instructions for upgrade from existing installation of recipes.

### ISSUE THREAD

**Issue by rrcook** [trailheadapps/lwc-recipes#375]
**What is missing from the application? Please describe.**
I'd like to see an upgrade path spelled out for someone who's installed an earlier version of the recipes into an org.

**Describe the solution you'd like**
If possible, add to the readme how to install the latest version of the recipes over an already-installed version of recipes in an org, or if that is not possible then instructions on how to wipe out the previous version before installing the latest.

**Comment by pchittum** [comment]
@rrcook how are you attempting the upgrade? Are you using the command line? Or do are you using the unlocked package install?

**Comment by rrcook** [comment]
I haven't tried anything yet, I was going to wait for advice on the best way to proceed.
I have a dev org with nothing in it but the recipes. I'm good with commands to wipe out what's there and install from an unlocked package, but I'd prefer to not create a new dev org, especially when there will be more upgrades in the future.
