### ISSUE TITLE
Error  force-app\main\default\layouts\Account-Account Layout.layout-meta.xml  In field: QuickAction - no QuickAction named FeedItem.RypplePost found

### ISSUE THREAD

**Issue by c0n5truct0r** [trailheadapps/lwc-recipes#376]
Hi Team,

I was unable to deploy the force-app to my developer org. When i try to deploy the force-app it was throwing below error.

SOURCE PROGRESS | ████████████████████████████████████████ | 178/179 Components
TYPE   PROJECT PATH                                                           PROBLEM
─────  ─────────────────────────────────────────────────────────────────────  ──────────────────────────────────────────────────────────────────────
Error  force-app\main\default\layouts\Account-Account Layout.layout-meta.xml  In field: QuickAction - no QuickAction named FeedItem.RypplePost found
ERROR running force:source:deploy:  Deploy failed.

**Comment by amarenderpasham** [comment]
Workaround: comment lines 181 - 183 from Account-Account Layout.layout-meta.xml and redeploy

**Comment by pchittum** [comment]
fix committed and reclosing
