### ISSUE TITLE
TodoList is not very helpful without the Todo component

### ISSUE THREAD

**Issue by dcarroll** [trailheadapps/lwc-recipes#38]
Seems like there is something missing.  There is no LWC component to create a Todo item, just the todoList that allows filtering an empty list of Todos.  Shouldn't there be more to this?

**Comment by muenzpraeger** [comment]
There is a LWC to create todo item’s, it’s the apiGetterSetter recipe.

https://github.com/trailheadapps/lwc-recipes/blob/master/force-app/main/default/lwc/apiSetterGetter/apiSetterGetter.html
