### ISSUE TITLE
Is there an example on how the circle ci was setup

### ISSUE THREAD

**Issue by brianbier** [trailheadapps/lwc-recipes#40]
I'm trying to use your circle ci example on my project but it keeps breaking. Is there information or documentation when setting it up?

Mine keeps failing on  the following below. I used my consumer key and user name from the connected app but it still doesn't register it.
 name: Authenticate DevHub
          command: |
              # if [[ $CIRCLE_BRANCH == prerelease* ]]; then
              # Temporary using pre-release till R2b (Spring '19 GA Launch')
              node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid $CONSUMERKEY_PRERELEASE --jwtkeyfile .circleci/server.key --username $USERNAME_PRERELEASE --setdefaultdevhubusername -a HubOrg
              # else
              #   node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile .circleci/server.key --username $USERNAME --setdefaultdevhubusername -a HubOrg
              # fi

**Comment by kevinv11n** [comment]
@ccoenraets @muenzpraeger  this could be a good topic for a blog post.

**Comment by muenzpraeger** [comment]
You can follow the instructions in this repo for Travis CI (which isn’t really different from CircleCI). The repo also links to the Trailhead module that gives you a full walk through for CI and DX.

https://github.com/forcedotcom/sfdx-travisci

**Comment by brianbier** [comment]
@kevinv11n  That would be a great Idea.
@muenzpraeger  The instructions worked perfectly but For some reason I run into a strange error:

ERROR: This session is not valid for use with the REST API.
 
It's happening at this line. For the connected app I gave it the full scope and all the other ones it suggested. Not sure how to allow the session to work with the rest api. 

`node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid $CONSUMERKEY_PRERELEASE --jwtkeyfile assets/server.key --username $USERNAME_PRERELEASE --setdefaultdevhubusername -a HubOrg`


I appreciate your help!

**Comment by muenzpraeger** [comment]
What's the output when you run the command locally?

**Comment by zaynelt** [comment]
> For the connected app I gave it the full scope and all the other ones it suggested.

@brianbier, Can you double-check that you've given 1.) just the scopes listed here (full scope isn't necessary, but you'll need api/web/refresh scopes), and 2.) configured the correct permissions for your ci user: https://trailhead.salesforce.com/content/learn/modules/sfdx_travis_ci/sfdx_travis_ci_connected_app

**Comment by brianbier** [comment]
@zaynelt  I Followed the instructions again and set the correct scopes and it still throws This session is not valid for use with the rest api

`sfdx force:auth:jwt:grant --clientid 3MVG9yZ.WNe6bHu --jwtkeyfile server.key --username bbier@salesforce.org --setdefaultdevhubusername --instanceurl https://login.salesforce.com`

**Comment by brianbier** [comment]
@zaynelt and @muenzpraeger 

So I kept getting the session not valid for use with rest api on my PBO ( production business org) with my user. 

I created another enterprise org and it seem to work with that org perfectly. Not sure why.

Also final question is how do you deal with the salesforce scratch org daily limits?

**Comment by muenzpraeger** [comment]
Glad that it's solved so far.

RE: scratch orgs - we have "custom" limits for our dev hub/sample apps. Depending on your flow you can look into moving scratch org creation into later parts or the process. And/or get add-on licenses for higher limits.
