### ISSUE TITLE
Date Picker and ComboBox Inputs do not Float over Modal Header and Footer

### ISSUE THREAD

**Issue by mfishco** [trailheadapps/lwc-recipes#402]
### Summary

Using the stock Modal recipe, I'm having difficulty getting content in the "body" (in the unnamed slot assigned the slds-modal__content class) to float on top of the header or footer.  Specifically, these are datepicker and combobox controls embedded in a different LWC component.   

### Steps To Reproduce:

1.  Create a LWC (crmGenericModal) consisting of only the Modal recipe markup, code and CSS currently posted on GitHub.
1.  Create a child LWC (testChild) consisting of a lightning layout containing a lightning-input of type "date" and a lightning-combobox.  Set up some values for the combobox in the JS.
```
<!-- Test Child -->
<template>
    <lightning-layout>
        <lightning-layout-item class="slds-p-around_small">
            <lightning-input
                    data-my-id="dateInput"
                    type="date"
                    name="sentDate"
                    label="Sent Date">
            </lightning-input>
        </lightning-layout-item>
        <lightning-layout-item class="slds-p-around_small">
            <lightning-combobox
                    name="sent"
                    label="Sent"
                    value={sentValue}
                    options={sentOptions}>
            </lightning-combobox>
        </lightning-layout-item>
    </lightning-layout>
</template>
```
```
//testChild.js
import {LightningElement} from 'lwc';

export default class TestChild extends LightningElement
{
	get sentOptions()
	{
		return[
			{ label: 'Sent', value: "true" },
			{ label: 'Not Sent', value: "false" }];
	}
}

```
3.  Create a parent LWC (testParent) embedding testChild in crmGenericModal
```
<!-- Test Parent -->
<template>
    <c-crm-generic-modal>
        <c-test-child></c-test-child>
    </c-crm-generic-modal>
</template>
```
4. Call the .show() method on the crmGenericModal in the renderedCallBack() of testParent
```import {LightningElement} from 'lwc';

export default class TestParent extends LightningElement
{
	renderedCallback()
	{
		const modalObj = this.template.querySelector('c-crm-generic-modal');
		modalObj.show();
	}
}
```
5. expand the date picker or the combobox and observe the results

### Expected result

The expanded datepicker or combox should float over the header/footer of the modal

### Actual result

The expanded datepicker or combobox is obscured by the header/footer of the modal.

![modalComboBox](https://user-images.githubusercontent.com/11182177/96305710-8a635a00-0fbb-11eb-82e9-62a2839f99be.png)

![modalDatePicker](https://user-images.githubusercontent.com/11182177/96305711-8afbf080-0fbb-11eb-8ec0-ae9206cfdb2f.png)

### Additional information

I've spent a fair bit of time trying z-index and some other attempts at manipulating the CSS but have been challenged to identify the actual elements that might have an effect.  Not sure if this is a bug or ignorance.  Thanks for taking a look.

**Comment by pchittum** [comment]
Thanks for reporting this @mfishco. I'll try to reproduce this in the next couple of weeks and keep you updated. Cheers.

**Comment by mfishco** [comment]
@pchittum My team lead took a look at the problem and after trying a bunch of complicated hard stuff, took a step back and had a think.  He was able to add the following CSS to crmGenericModal:

`.slds-modal__content{
    overflow: initial;
    overflow-y: initial;
}`

This allowed the calendar and combobox components to float over the header and footer when expanded.

Thank you for offering to spend the time on the issue.  For my part, it can be closed.  If I can provide any further information, please feel free to reach out.  Hopefully this information is helpful to you and the LWC team.

Mitch 
![image](https://user-images.githubusercontent.com/11182177/97434769-1c852f80-18e5-11eb-9295-39c70831544c.png)

**Comment by pchittum** [comment]
@mfishco, I'm setting aside time to look into this this week. 

I'm glad you have it working. It looks as if you're overriding an SLDS class. Generally this should be avoided. I can't tell you to not do that, but feel obliged to point that out. I'll take a stab and look to see if there's a way we can offer to our developers that doesn't override the slds classes.

**Comment by mfishco** [comment]
Thanks @pchittum !  Looking forward to seeing what you come up with.  We aren't going to prod for a few weeks so if there is a better way, there is still a way to get it into the code.  Good luck!
