### ISSUE TITLE
ISSUE ON :Parent-to-Child - ApiSetterGetter component

### ISSUE THREAD

**Issue by Isthiyaqsforce-P** [trailheadapps/lwc-recipes#408]
### Summary
I have installed the LWC-Recipes in the developer org via unlocked package

### Steps To Reproduce:

1. Navigate to the Parent to child tab
2. In Api SetterGetter Component , Add the description
3. Now click on the Add Todo Button 
4. Now Press left click on the Add Todo Button outside of the Add Todo Button 
5. You can still see the todo list getting added
 
### Expected result

it should not create todo list 

### Actual result

it is creating the todo list

### Additional information

Video evidence
https://drive.google.com/file/d/1pdkVoItqqWL9vKMEEMXEMUfgwsd2mGC-/view?usp=sharing

Browser : Chrome
Chrome Version : 86.0.4240.111
OS : WINDOW 10

**Comment by pchittum** [comment]
Nice catch. I'll take a look at this and see what we can do to fix it.

**Comment by pchittum** [comment]
Making progress. Should be able to have fix today or Monday.
