### ISSUE TITLE
apply css to rest api response html content in LWC

### ISSUE THREAD

**Issue by madhusitams004** [trailheadapps/lwc-recipes#451]
**What is missing from the application? Please describe.**
I am calling one rest call in LWC js and getting response as HTML content. while displaying that html content in component I'd like to apply css

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pchittum** [comment]
Hi @madhusitams004. Can you tell me more about this use case? Are you looking for us to add a recipe that demonstrates what you're asking? Or asking how to do this? 

This seems like a question that would be better put to salesforce.stackexchange.com.
