### ISSUE TITLE
Add always-throws-error recipe components to Apex pages.

### ISSUE THREAD

**Issue by pchittum** [trailheadapps/lwc-recipes#462]
**What is missing from the application? Please describe.**
Error and exception handling exists across much of the sample app. However creating the error conditions so you can see those is not always straightforward (for instance you can get some components to display errors by not loading data). We should have some components that always display errors to visually demonstrate those best practices. 

**Describe the solution you'd like**
Add the following demo-level components
- `apexWireError`
- `apexImperativeError`

To support these we'd also need the following
- New method in `ContactController.cls` apex class that always throws a custom exception
- New inner exception subclass in `ContactController` class called `CustomException`
- Jest tests for `apexImperativeError` and `apexWireError`. 

**Describe alternatives you've considered**
Instructions in the README that describe how to force errors on existing components. This is less than ideal, especially if we want to display error surfacing/handling in both an `@wire` context and an imperative Apex call via `promise.catch`, as not all the existing components surface an error (specifically, there's no imperative apex component that does).

**Additional context**
This requirement came about from work and discussion on Issue #445, and PRs #446 and #453.

**Comment by pchittum** [comment]
@rahulmalhotra, I've moved tracking of these new recipes to this Issue. I'm going to get the components in place today. I'd welcome your contributions, if you have time to write the jest tests for these. Let me know if you have the time. Otherwise I'll pick them up early next week and finish them. 

You can PR against the branch `pc/issue-462-apex-errors`.

**Comment by pchittum** [comment]
@rahulmalhotra, I've added stubbed out lwc tests to the `pc/issue-462-apex-errors` branch now. I'll be otherwise occupied for the rest of today. But let me know how you get on.

**Comment by rahulmalhotra** [comment]
Thank you for the update @pchittum , Apologies, I am just too stuck in some company projects nowadays, not getting any time to work on this. Will update you on the same by this weekend.
