### ISSUE TITLE
Remove unsupported package - `@salesforce/eslint-plugin-aura`

### ISSUE THREAD

**Issue by trevor-bliss** [trailheadapps/lwc-recipes#469]
### Summary

The `@salesforce/eslint-plugin-aura` package is not officially supported by the Aura team. It is also not the same linter used in the `sfdx force:lightning:lint` command. This project should only use officially supported tools with proper owners.

### Additional information

https://github.com/forcedotcom/eslint-plugin-aura

**Comment by pozil** [comment]
I'll take care of this as it impacts these 4 sample apps:
- lwc-recipes
- dreamhouse-lwc
- easy-spaces-lwc
- automation-components

**Comment by pozil** [comment]
Based on the internal discussions about the future of the `sfdx force:lightning:lint` command, I'm closing this issue while waiting for a `@salesforce/eslint-plugin-aura` update.
