### ISSUE TITLE
Installed package error in pre-release sandbox

### ISSUE THREAD

**Issue by kccrs** [trailheadapps/lwc-recipes#47]
> Your request to install package "LWCRecipes Spring '19" was unsuccessful. None of the data or setup information in your salesforce.com organization was affected.
> 
> Package: LWCRecipes (04tB0000000YGYO)
> Error Number: 1911984685-17123 (-938529298)
> Problem:
> 
> 1. (recipes) In field: field - no CustomField named Contact.CleanStatus found
> recipes: In field: field - no CustomField named Contact.CleanStatus found

I've tried installing both with and without adding a custom field called CleanStatus, I get the same error regardless.  Have tried in both developer org and full sandbox.

**Comment by muenzpraeger** [comment]
Fixed by #55
