### ISSUE TITLE
objectApiName property is not passed with object api name.

### ISSUE THREAD

**Issue by sankaran1984** [trailheadapps/lwc-recipes#490]
https://github.com/trailheadapps/lwc-recipes/blob/738dae3f1989ca975430fcdaf08a8a7877eef894/force-app/main/default/lwc/ldsGenerateRecordInputForCreate/ldsGenerateRecordInputForCreate.js#L21

In this line, i think objectApiName should be passed instead of ACCOUNT_OBJECT object.

It believe, it should be like this,
@wire(getRecordCreateDefaults, { objectApiName: ACCOUNT_OBJECT.objectApiName })

**Comment by SasidharanA** [comment]
https://sfdcsasid.blogspot.com/2022/06/how-to-get-recordid-and-objectapiname.html please refer this link for this issue reported and let me know your feedback on it.
