### ISSUE TITLE
Rename ApiFunction recipe name to align with docs

### ISSUE THREAD

**Issue by pozil** [trailheadapps/lwc-recipes#493]
The `ApiFunction` recipe should be named `ApiMethod` to better align with our [documentation](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.create_javascript_methods) (we use the term "public method" rather than "public function").

Please rename the method and update the recipe description accordingly.

**Comment by satyasekharcvb** [comment]
Working on it!

**Comment by satyasekharcvb** [comment]
This issue is fixed in #505
