### ISSUE TITLE
Issues pushing into a Spring19 DevHub preview org

### ISSUE THREAD

**Issue by jonny2k9** [trailheadapps/lwc-recipes#5]
Hi There,

I am pushing the source into a Spring19 DevHub preview org and receiving the following errors:

PROJECT PATH                                                                ERROR
──────────────────────────────────────────────────────────────────────────  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
force-app\main\default\flexipages\Hello.flexipage-meta.xml                  We couldn't retrieve the design time component information for component c:hello.
force-app\main\default\flexipages\Events.flexipage-meta.xml                 We couldn't retrieve the design time component information for component c:eventSimple.
force-app\main\default\flexipages\X3rd_Party_Libs.flexipage-meta.xml        We couldn't retrieve the design time component information for component c:libsD3.
force-app\main\default\flexipages\Wire.flexipage-meta.xml                   We couldn't retrieve the design time component information for component c:apexWireMethodToProperty.
force-app\main\default\flexipages\Data_Service.flexipage-meta.xml           We couldn't retrieve the design time component information for component c:lds.
force-app\main\default\flexipages\Contact_Record_Page.flexipage-meta.xml    We couldn't retrieve the design time component information for component c:recordFormDynamicContact.
force-app\main\default\flexipages\Composition.flexipage-meta.xml            We couldn't retrieve the design time component information for component c:compositionBasics.
force-app\main\default\flexipages\Aura_Interoperability.flexipage-meta.xml  We couldn't retrieve the design time component information for component c:pubsubContactList.
force-app\main\default\flexipages\Apex.flexipage-meta.xml                   We couldn't retrieve the design time component information for component c:apexWireMethodToProperty.
force-app\main\default\aura\auraPubsubPublisher\auraPubsubPublisher.cmp     No COMPONENT named markup://c:auraPubsub found : [markup://c:auraPubsubPublisher]
force-app\main\default\aura\auraPubsubSubscriber\auraPubsubSubscriber.cmp   No COMPONENT named markup://c:auraPubsub found : [markup://c:auraPubsubSubscriber]
force-app\main\default\aura\auraDomEventListener\auraDomEventListener.cmp   No COMPONENT named markup://c:categoryFilter found : [markup://c:auraDomEventListener]
force-app\main\default\flexipages\Misc_Techniques.flexipage-meta.xml        We couldn't retrieve the design time component information for component c:miscGetUserId.
force-app\main\default\flexipages\Navigation.flexipage-meta.xml             We couldn't retrieve the design time component information for component c:navToHome.
force-app\main\default\flexipages\Parent_to_Child.flexipage-meta.xml        We couldn't retrieve the design time component information for component c:apiProperty.
force-app\main\default\flexipages\Pub_Sub.flexipage-meta.xml                We couldn't retrieve the design time component information for component c:pubsubSearchBar.
N/A                                                                         Main markup cannot be empty. If you are trying to delete the Lightning definition bundle, directly delete the bundle instead.
N/A                                                                         Main markup cannot be empty. If you are trying to delete the Lightning definition bundle, directly delete the bundle instead.
N/A                                                                         Main markup cannot be empty. If you are trying to delete the Lightning definition bundle, directly delete the bundle instead.
force-app\main\default\tabs\Navigation.tab-meta.xml                         In field: flexiPage - no FlexiPage named Navigation found
force-app\main\default\tabs\Misc_Techniques.tab-meta.xml                    In field: flexiPage - no FlexiPage named Misc_Techniques found
force-app\main\default\tabs\Hello.tab-meta.xml                              In field: flexiPage - no FlexiPage named Hello found
force-app\main\default\tabs\Events.tab-meta.xml                             In field: flexiPage - no FlexiPage named Events found
force-app\main\default\tabs\Data_Service.tab-meta.xml                       In field: flexiPage - no FlexiPage named Data_Service found
force-app\main\default\tabs\Composition.tab-meta.xml                        In field: flexiPage - no FlexiPage named Composition found
force-app\main\default\applications\LWC_Recipes.app-meta.xml                In field: tab - no CustomTab named Hello found
force-app\main\default\tabs\Apex.tab-meta.xml                               In field: flexiPage - no FlexiPage named Apex found
force-app\main\default\tabs\X3rd_Party_Libs.tab-meta.xml                    In field: flexiPage - no FlexiPage named X3rd_Party_Libs found
force-app\main\default\tabs\Wire.tab-meta.xml                               In field: flexiPage - no FlexiPage named Wire found
force-app\main\default\tabs\Pub_Sub.tab-meta.xml                            In field: flexiPage - no FlexiPage named Pub_Sub found
force-app\main\default\tabs\Parent_to_Child.tab-meta.xml                    In field: flexiPage - no FlexiPage named Parent_to_Child found
force-app\main\default\tabs\Aura_Interoperability.tab-meta.xml              In field: flexiPage - no FlexiPage named Aura_Interoperability found
force-app\main\default\permissionsets\recipes.permissionset-meta.xml        In field: tab - no CustomTab named Apex found
N/A                                                                         We couldn't validate your component. Review it and try again. The following code has invalid references which caused safe validation failure. AuraDefinition [
                                                                            id:null
                                                                            deftype:null
                                                                            format:null
                                                                            source:
                                                                            null] (0:0)
N/A                                                                         We couldn't validate your component. Review it and try again. The following code has invalid references which caused safe validation failure. AuraDefinition [
                                                                            id:null
                                                                            deftype:null
                                                                            format:null
                                                                            source:
                                                                            null] (0:0)
N/A                                                                         We couldn't validate your component. Review it and try again. The following code has invalid references which caused safe validation failure. AuraDefinition [
                                                                            id:null
                                                                            deftype:null
                                                                            format:null
                                                                            source:
                                                                            null] (0:0)

**Comment by muenzpraeger** [comment]
Can you please verify that you're actually using the pre-release dev hub? That error looks like you're pushing to a Winter '19, and not a Spring '19 org.

Run `sfdx force:org:list`, that'll show you the authenticated orgs. If your dev hub is not the default dev hub (has a `(D)` before it's name), then you've to pass the parameter `-v yourdevhubname` when creating a scratch org.

**Comment by jonny2k9** [comment]
I can verify that I am using a Spring 19 dev hub as Einstein is wheeling on his bicycle when I open the scratch org. I tried logging out of my old dev hub, re-authing with my Spring 19 dev hub, and the errors are still showing up when pushing the source.

**Comment by muenzpraeger** [comment]
If you run `sfdx plugins —core` - do you run the needed pre-release version of the `salesforcedx` plugin, as documented in the readme?

**Comment by jonny2k9** [comment]
Thankyou @muenzpraeger!

**Comment by AnamikaRathoreJandu** [comment]
@jonny2k9 Did you ever find a solution for this? I'm having the same issue deploying to a sandbox which is on cs102. According to salesforce this was fixed on cs102 as part of Spring 19 patch fix but it still persists? Right now the only way I can get a green build is if I add the flexipage in gitognore. I'd be really glad if you could help me out :)

Thanks!

**Comment by muenzpraeger** [comment]
@AnamikaRathoreJandu The issue from @jonny2k9 can't exist as of today.

Please post your error message, so that we can drill down on your issue.

**Comment by AnamikaRathoreJandu** [comment]
@muenzpraeger  this is the build error that I get when deploying a lightning app called workforce monitor which is added to our consoles.
------------
Error  deploy_build/flexipages/eco_sales_UtilityBar.flexipage    eco_sales_UtilityBar    We couldn't retrieve the design time component information for component mwm:WorkforceMonitor.
Error  deploy_build/flexipages/eco_service_UtilityBar.flexipage  eco_service_UtilityBar  We couldn't retrieve the design time component information for component mwm:WorkforceMonitor.

**Comment by muenzpraeger** [comment]
That’s not related to the Recipes application. I recommend to reach out on Stackexchange.

**Comment by AnamikaRathoreJandu** [comment]
@muenzpraeger Oh no, I only paid attention to the actual error so thought could get some help here. Thanks for that :)
