### ISSUE TITLE
Where are the public getter/setters in this recipe?

### ISSUE THREAD

**Issue by ericrsmith35** [trailheadapps/lwc-recipes#504]
https://github.com/trailheadapps/lwc-recipes/blob/main/force-app/main/default/lwc/apiSetterGetter/apiSetterGetter.js

I got here based on the link is this article (https://developer.salesforce.com/blogs/2021/05/inter-component-communication-patterns-for-lightning-web-components.html) saying this is an example of the @api Get, Set dicussed in the original post.

**Comment by satyasekharcvb** [comment]
Hi Eric, The child component [toDoList(c-todo-list)](https://github.com/trailheadapps/lwc-recipes/blob/main/force-app/main/default/lwc/todoList/todoList.js) contains the public getters and setters(get todos and set todos methods). The apiSetterGetter is the parent component. 
You can also find one more [example](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/js_props_getters_setters) in the LWC Developer guide.

**Comment by ericrsmith35** [comment]
Thank you, I missed that.
