### ISSUE TITLE
Installing Recipes using Salesforce DX: Deployment Failed

### ISSUE THREAD

**Issue by karamchandaniD** [trailheadapps/lwc-recipes#51]
While deploying build using Salesforce DX, in scratch-org or pre-released org) facing issues: https://prnt.sc/mhigh5

Anyone having ideas for solution - Please share!

**Comment by muenzpraeger** [comment]
That actually looks like you’re deploying to an org that’s not on pre-release.

**Comment by karamchandaniD** [comment]
Deploying build to a Scratch org connected to Pre-release org.
Having spring '19 feature.

Installed Recipes using an Unlocked Package, worked fine!

any solution for SF-DX deployment?

**Comment by Sheing** [comment]
I have this same error before, it was due to SFDX versioning issue. Try `sfdx -v` and make sure the version is >v6.50.

**Comment by karamchandaniD** [comment]
Thanks @Sheing - for sharing updates, it helped me to fix that situation.

<y sfdx version is updated but not having pre-release plugins so I includes those as well and now working fine.

Info: if someone face the same please use following command to update plugin library:
sfdx plugins:install salesforcedx@pre-release
