### ISSUE TITLE
Add modal overlay example

### ISSUE THREAD

**Issue by muenzpraeger** [trailheadapps/lwc-recipes#57]
Currently there is no base component provided that shows how to use the SLDS modal

**Comment by tsalb** [comment]
I am waiting on this as well for full migration!

**Comment by cnaccio** [comment]
Here's a modal we developed in our application. Hope it helps!


[modal.zip](https://github.com/trailheadapps/lwc-recipes/files/2943311/modal.zip)

**Comment by muenzpraeger** [comment]
Fixed via #91
