### ISSUE TITLE
Multiple Failures When Deploying to Winter '22 Sandbox Org

### ISSUE THREAD

**Issue by chrisbanm** [trailheadapps/lwc-recipes#586]
### Summary

I cloned the repo today and attempted to perform a deploy to a new existing sandbox org. During the deploy 31 failures were recorded:

`Component Failures [31]
===================================================================================================
| Type  Name                   Problem
| ───── ────────────────────── ────────────────────────────────────────────────────────────────────
| Error LWC_Recipes            In field: tab - no CustomTab named Hello found
| Error Contact.CleanStatus    Could not resolve standard field's name. (138:61)
| Error Apex                   In field: flexiPage - no FlexiPage named Apex found
| Error Aura_Interoperability  In field: flexiPage - no FlexiPage named Aura_Interoperability found
| Error Composition            In field: flexiPage - no FlexiPage named Composition found
| Error Data_Service           In field: flexiPage - no FlexiPage named Data_Service found
| Error Events                 In field: flexiPage - no FlexiPage named Events found
| Error Hello                  In field: flexiPage - no FlexiPage named Hello found
| Error Message_Service        In field: flexiPage - no FlexiPage named Message_Service found
| Error Misc_Techniques        In field: flexiPage - no FlexiPage named Misc_Techniques found
| Error Navigation             In field: flexiPage - no FlexiPage named Navigation found
| Error Parent_to_Child        In field: flexiPage - no FlexiPage named Parent_to_Child found
| Error Wire                   In field: flexiPage - no FlexiPage named Wire found
| Error X3rd_Party_Libs        In field: flexiPage - no FlexiPage named X3rd_Party_Libs found
| Error Apex                   Property 'identifier' not valid in version 52.0 (9:32)
| Error Aura_Interoperability  Property 'identifier' not valid in version 52.0 (5:32)
| Error Composition            Property 'identifier' not valid in version 52.0 (9:32)
| Error Contact_Record_Page    Property 'identifier' not valid in version 52.0 (5:32)
| Error Data_Service           Property 'identifier' not valid in version 52.0 (5:32)
| Error Events                 Property 'identifier' not valid in version 52.0 (9:32)
| Error Hello                  Property 'identifier' not valid in version 52.0 (9:32)
| Error Message_Service        Property 'identifier' not valid in version 52.0 (9:32)
| Error Misc_Techniques        Property 'identifier' not valid in version 52.0 (9:32)
| Error Navigation             Property 'identifier' not valid in version 52.0 (9:32)
| Error Parent_to_Child        Property 'identifier' not valid in version 52.0 (9:32)
| Error Wire                   Property 'identifier' not valid in version 52.0 (9:32)
| Error X3rd_Party_Libs        Property 'identifier' not valid in version 52.0 (9:32)
| Error recipes                In field: tab - no CustomTab named Apex found
| Error CompositionWalkthrough Target page is unsupported.
| Error DataWalkthrough        Target page is unsupported.
| Error HelloWalkThrough       Target page is unsupported.`

### Salesforce Org Type

Sandbox Org

### Steps To Reproduce

I did exactly what the read me instructed me to do up to the point of the deploy.

### Current Behavior

Returns 31 failures

### Expected Behavior

A successful deploy

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by satyasekharcvb** [comment]
Closing this issue as it is a non-issue and no response for a while.
