### ISSUE TITLE
Deploying to Trailhead playground failed

### ISSUE THREAD

**Issue by Conner1341** [trailheadapps/lwc-recipes#587]
### Summary

Tried to deploy to a brand new Trailhead Playground using `sfdx force:source:deploy -p force-app` and received a Component Failure with the following error message: "Error  pubsub  An object 'pubsub' of type LightningComponentBundle was named in package.xml, but was not found in zipped directory".  

Playground is on API version 53.0 and the latest CLI is installed - 7.124.0

### Salesforce Org Type

Trailhead Playground

### Steps To Reproduce

1. Create a brand-new Trailhead playground
2. Cloned this repository
3. Authorized the playground
4. Ran `sfdx force:source:deploy -p force-app` from the terminal w/in VSCode

### Current Behavior

Followed steps 1-3 in the README for installing the app in a Trailhead Playground. After running `sfdx force:source:deploy -p force-app`, the deploy fails and I cannot continue installing the app.

### Expected Behavior

Expected successful deploy.

### Relevant Log Output

```shell
$ sfdx force:source:deploy -p force-app

*** Deploying with SOAP API ***
Deploy ID: 0Af5f00000B9R92CAF
SOURCE PROGRESS | ████████████████████████████████████████ | 187/188 Components

=== Component Failures [1]
Type   Name    Problem
─────  ──────  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error  pubsub  An object 'pubsub' of type LightningComponentBundle was named in package.xml, but was not found in zipped directory

ERROR running force:source:deploy:  Deploy failed.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sridhar-Trancoserv** [comment]
any updates on this one, i am getting the same error?

**Comment by satyasekharcvb** [comment]
Hi @Sridhar-Trancoserv, Sorry for the delayed response. The issue will be fixed on the next working day. 
**Workaround, for Now,**: if you delete the `pubsub` folder from the `force-app/main/default/lwc` folder, it will work.

**Comment by parte-mandar** [comment]
It works in 2022
