### ISSUE TITLE
Add account Id parameter passing to controller example

### ISSUE THREAD

**Issue by chandra2ravi** [trailheadapps/lwc-recipes#59]
Please add ID of the record passing to controller and display based on ID.
Pass account Id and display related contacts

**Comment by muenzpraeger** [comment]
@chandra2ravi Can you please specify what's missing?

The recordForm* recipes show how to use base lightning components to get record data:
https://github.com/trailheadapps/lwc-recipes/tree/master/force-app/main/default/lwc

These recipes show how to get record data using wire service (UI API):
https://github.com/trailheadapps/lwc-recipes/tree/master/force-app/main/default/lwc/wireGetRecordStaticContact
https://github.com/trailheadapps/lwc-recipes/tree/master/force-app/main/default/lwc/wireGetRecordDynamicContact

These recipes show how to pass data to an Apex controller (only recommended if UI API doesn't fulfil your needs):
https://github.com/trailheadapps/lwc-recipes/tree/master/force-app/main/default/lwc/apexWireMethodWithParams
https://github.com/trailheadapps/lwc-recipes/tree/master/force-app/main/default/lwc/apexImperativeMethodWithParams

**Comment by chandra2ravi** [comment]
Thanks for the explanation with example. We need one example with passing reocrd id and return list<wrapper> /Map.

**Comment by muenzpraeger** [comment]
That can be any of the existing Apex examples.

**Comment by chandra2ravi** [comment]
I tried it but no luck from 2 days.
 @AuraEnabled(Cacheable=true)
    public static Map<String, FieldValidationResults>  getAccounts( string accountId ){
 // fill map
   return actValidationResults;
}

@wire(getAccounts, { accountId: '$recordId' })
wiredGetAccounts(value) {
 this.wiredAccounts = value;
//I'm getting undefined and not able to see map values
}

**Comment by zaynelt** [comment]
When you use the @wire decorator for a function, the platform will provision the information returned to either a 'data' or 'error' attribute. The 'wiredGetAccounts' function isn't formatted to handle these values in your snippet.

See the 'Decorate a Function' section of the docs here: https://developer.salesforce.com/docs/component-library/documentation/lwc/data_wire_service_about

You can see this in action in the 'apexWireMethodToFunction' recipe: https://github.com/trailheadapps/lwc-recipes/blob/master/force-app/main/default/lwc/apexWireMethodToFunction/apexWireMethodToFunction.js

**Comment by chandra2ravi** [comment]
still, i'm getting undefined, do we need to import wrapper class?

wiredGetAccounts({ error, data }) {
  if (data) {
   this.accounts = data;
   const rtis =  this.accounts;
   console.log(  Object.keys(rtis) );
   console.log(  Object.values(rtis) );
   Object.keys(rtis).forEach(function(key) {
    console.log(  key );
    let  wrap = rtis[key];
    console.log(  wrap );
console.log(  wrap.maxLength );//undefined here
});
   this.error = undefined;
 } else if (error) {
   this.error = error;
   this.contacts = undefined;
 }
}

Wrapper: 
public with sharing class AccountHealthCheckController {
public class FieldValidationResults {
        public boolean filled{get;set;}         
                                                  
        public integer maxLength{get;set;}    
        public integer length{get;set;}        
        public boolean lengthValid{get;set;}   
        public boolean ownerValid{get;set;}
    }   
 @AuraEnabled(Cacheable=true)
    public static Map<String, FieldValidationResults>  getAccounts( string accountId ){
     Map<String, FieldValidationResults> validationResults = new Map<String, FieldValidationResults>();
//logic
return validationResults ;
}
}
![image](https://user-images.githubusercontent.com/93057/53128474-8521e380-352a-11e9-9084-134a44af6657.png)

**Comment by zaynelt** [comment]
You should check out the 'customerServices' Apex class and 'customerList' Lightning web component in Easy Spaces. The customerList component calls an Apex method that returns a wrapper class and @auraEnabled properties, and processes the results with a wired function.

The customerList controller: https://github.com/trailheadapps/easy-spaces-lwc/blob/develop/es-space-mgmt/main/default/lwc/customerList/customerList.js

The customerServices Apex (which is the Apex class where the inner/wrapper class and properties are defined): https://github.com/trailheadapps/easy-spaces-lwc/blob/develop/es-base-code/main/default/classes/customerServices.cls

**Comment by chandra2ravi** [comment]
@zaynelt 
🙏🙏🙏🙏
