### ISSUE TITLE
Example of nested modals

### ISSUE THREAD

**Issue by joeythomaschaske** [trailheadapps/lwc-recipes#613]
### Summary

I'd like to see an example of creating nested modals.

A nested modal may happen when while creating a new record, it requires a lookup record that needs to be created as well.

Here is an example of out of the box salesforce and nested modals: 

![Screen Shot 2021-12-29 at 8 32 36 PM](https://user-images.githubusercontent.com/7061638/147717961-d5b7ef65-83d1-41fe-9838-b0768fedef89.png)

it is unclear how to properly use nesting with modals in the SLDS documentation and the recipes repo

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by satyasekharcvb** [comment]
Hi @joeythomaschaske, Thank you for submitting the request. We will review and work on it.

**Comment by satyasekharcvb** [comment]
This example can be an extension of the existing [MiscModal](https://github.com/trailheadapps/lwc-recipes/tree/main/force-app/main/default/lwc/miscModal) recipe. Can you please check that recipe? You can find more discussion on that in this [PR](https://github.com/trailheadapps/lwc-recipes/pull/91).
