### ISSUE TITLE
datatableCustomDataType html link to github source typo

### ISSUE THREAD

**Issue by jdpond** [trailheadapps/lwc-recipes#618]
### Summary

Typo in html link to github
source="lwc/datataleCustomDataType" should be source="lwc/datatableCustomDataType"

### Salesforce Org Type

Trailhead Playground

### Steps To Reproduce

When running in LWC Application click on 

### Current Behavior
![image](https://user-images.githubusercontent.com/271131/148319549-3385ac76-c37e-454e-90b8-144aed3a6e34.png)

![image](https://user-images.githubusercontent.com/271131/148315075-eeba7467-f2ee-4912-84a3-49bc6523a2ae.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/271131/148315282-d71d1bd1-1540-405f-a442-d3f7b327c2a4.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by satyasekharcvb** [comment]
Hi @jdpond, Thank you for pointing this. It will be fixed with the next merge.

**Comment by satyasekharcvb** [comment]
Hi @jdpond, Merged the changes :)
