### ISSUE TITLE
recordFormDynamicContact - odd fields / multiple columns

### ISSUE THREAD

**Issue by acann22** [trailheadapps/lwc-recipes#625]
### Summary

Using the lightning-record-form syntax, if you have an odd number of fields compared to the number of columns, the trailing field on the left hand side stretches across all the columns which isn't the best UI/UX. Would love to see this address so the styling is consistent.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by satyasekharcvb** [comment]
Thanks for pointing this @acann22. This is the default behavior of the lightning-record-form. The design decision might be to avoid the white space, but as you said, if it just fills column one, it looks good. We will raise an internal ticket with the Base components team.
