### ISSUE TITLE
AuraException doesn't works

### ISSUE THREAD

**Issue by AjManoj** [trailheadapps/lwc-recipes#65]
Throwing aura exception is broken in lightning web components

Received following as error in JavaScript:
"{"ok":false,"status":400,"statusText":"Bad Request","body":{"message":"An internal server error has occurred\nError ID: 1033509552-45173 (-1981970979)"}}"

**Comment by muenzpraeger** [comment]
@kevinv11n

**Comment by muenzpraeger** [comment]
@AjManoj can you please paste the Apex code that you used here? Thanks!

**Comment by AjManoj** [comment]
@auraenabled
public static void throwexceptionmethod(){
 throw new AuraException('Custom message');
}

**Comment by muenzpraeger** [comment]
We're investigating. Thanks!

**Comment by kevinv11n** [comment]
That is the expected behavior in Spring 19. It is consistent between LWC and Aura components.

We're working on an update where we'll surface the message of the AuraException along with some stack information. This should land in the next few releases. #SafeHarbor
