### ISSUE TITLE
set default value while navigate to new record

### ISSUE THREAD

**Issue by sanketadi** [trailheadapps/lwc-recipes#66]
I could not find a way to set default values for the field while navigating to new record using below piece of code:-

`import { LightningElement } from 'lwc';
import { NavigationMixin } from 'lightning/navigation';

export default class NavToNewRecord extends NavigationMixin(LightningElement) {
    navigateToNewContact() {
        this[NavigationMixin.Navigate]({
            type: 'standard__objectPage',
            attributes: {
                objectApiName: 'Contact',
                actionName: 'new'
            }
        });
    }
}`

**Comment by muenzpraeger** [comment]
Setting default values isn't yet supported, and planned for an upcoming release.

**Comment by whaliim** [comment]
Hello, sorry for reopening this thread. Is there any update on this? I have searched on 
[Lightning Component Library](https://developer.salesforce.com/docs/component-library/bundle/lightning-navigation/documentation) and overall on The Internet, I have not found any info or update on this. Thank you.

**Comment by muenzpraeger** [comment]
@whaliim Coming soon, I think.

**Comment by ericfSF** [comment]
Navigate to a Record’s Create Page with Default Field Values
[](https://releasenotes.docs.salesforce.com/en-us/spring20/release-notes/rn_general_lex_navigate_to_record_dfv.htm)
