### ISSUE TITLE
how to use dynamic field and dynamic value  as a default value

### ISSUE THREAD

**Issue by Sourabh42** [trailheadapps/lwc-recipes#685]
### Summary

how to add dynamic value and dynamic field in navigation state context

### Salesforce Org Type

Developer Edition Org

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by satyasekharcvb** [comment]
Hi @Sourabh42, Thank you for the idea. We will review and implement it.

**Comment by adityanaag3** [comment]
Hi @Sourabh42 - The `defaultValues` is just a JavaScript object with field names as keys, and field values as values. So you should be able to dynamically create or modify that JavaScript object before passing it to the Navigate function.

For example, here is how you could modify the [NavToNewRecordWithDefaults](https://github.com/trailheadapps/lwc-recipes/tree/main/force-app/main/default/lwc/navToNewRecordWithDefaults) recipe to send dynamic fields and values.

```
export default class NavToNewRecordWithDefaults extends NavigationMixin(
    LightningElement
) {
    // An object that stores default values for the sObject
    obj = {
        FirstName: 'Morag',
        LastName: 'de Fault',
    };

    companyName = 'Demo';
    newFieldName = 'Company';

    connectedCallback(){
        // Dynamically adding a static field name and value
        this.obj.LeadSource = 'Other';
        this.obj.LastName = 'Some other name';

        // Dynamically adding a dynamic field name and value
        this.obj[this.newFieldName] = this.companyName;
    }

    navigateToNewContactWithDefaults() {

        const defaultValues = encodeDefaultFieldValues(this.obj);

```

Hope this answers your question. If not, please elaborate on your question and I'll be happy to help.

**Comment by satyasekharcvb** [comment]
I hope the above answer is helpful. As there is no further reply for a while closing this issue.
