### ISSUE TITLE
Unable to add new property to @Track variable 

### ISSUE THREAD

**Issue by chandra2ravi** [trailheadapps/lwc-recipes#69]
@zaynelt 
1. Unable to add new property in  @track account;
need new js variable content and iconname. Can you please let me know how can i add?
![image](https://user-images.githubusercontent.com/93057/53524445-020e0980-3aa5-11e9-9229-3f2e9f4c2167.png)

2 The below tag not working with dynamic data it displayed  {accounts.Name.length}  instead of number 10
lightning-helptext content="Current length of {accounts.Name.length} exceeds {accounts.Name.maxLength} char maximum." icon-name="utility:error" icon-variant="error" size="x-small"></lightning-helptext

====

**Comment by zaynelt** [comment]
In your code sample, it looks like you're trying to add your properties by using dot notation on the data returned to your @wire method. If you want to create and display custom properties like 'content' or 'iconname', you should look at declaring these properties using get/set patterns, as the docs explain: https://developer.salesforce.com/docs/component-library/documentation/lwc/js_props_getter

A basic recipe for this is here: https://github.com/trailheadapps/lwc-recipes/tree/master/force-app/main/default/lwc/helloExpressions

**Comment by chandra2ravi** [comment]
I have 20 conditions to add if i can add one place it can be easy. what about 2 question "{accounts.Name.length} instead of number 10"
![image](https://user-images.githubusercontent.com/93057/53525574-b7da5780-3aa7-11e9-88c3-f1a767126cc1.png)

**Comment by kevinv11n** [comment]
1 - Data provisioned by `@wire` is immutable. From https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.data_wire_service_about, _The wire service provisions an immutable stream of data to the component. Each value in the stream is a newer version of the value that precedes it._

In your first code sample, `this.account` is assigned a provisioned value. `this.account.Name.Content`is trying to mutate that immutable value so it throws. 


2 - LWC components do not support Aura's expression language. Refer to 
https://developer.salesforce.com/docs/component-library/documentation/lwc/migrate_expressions for guidance.

**Comment by chandra2ravi** [comment]
![image](https://user-images.githubusercontent.com/93057/54066724-c688e300-41fa-11e9-9a76-8ea782f08224.png)

here data is immutable but i'm copying data to account (mutable)
@kevinv11n

**Comment by muenzpraeger** [comment]
What you are doing is assigning the immutable value of `data` to your `account` property. That doesn’t make it mutable, as JavaScript copies object values by reference.
