### ISSUE TITLE
Errors from force:source:push 

### ISSUE THREAD

**Issue by jmlewis2** [trailheadapps/lwc-recipes#7]
I'm getting the errors below pushing to a scratch org which I'm sure is Spring19 (logo is Einstein riding a bike, instance is cs46 which seems unrecognised by status.salesforce.com).

force-app/main/default/aura/auraDomEventListener/auraDomEventListener.cmp   No COMPONENT named markup://c:categoryFilter found : [markup://c:auraDomEventListener]
force-app/main/default/aura/auraPubsubPublisher/auraPubsubPublisher.cmp     No COMPONENT named markup://c:auraPubsub found : [markup://c:auraPubsubPublisher]
force-app/main/default/flexipages/X3rd_Party_Libs.flexipage-meta.xml        We couldn't retrieve the design time component information for component c:libsD3.
force-app/main/default/flexipages/Wire.flexipage-meta.xml                   We couldn't retrieve the design time component information for component c:apexWireMethodToProperty.
force-app/main/default/aura/auraPubsubSubscriber/auraPubsubSubscriber.cmp   No COMPONENT named markup://c:auraPubsub found : [markup://c:auraPubsubSubscriber]
force-app/main/default/flexipages/Apex.flexipage-meta.xml                   We couldn't retrieve the design time component information for component c:apexWireMethodToProperty.
force-app/main/default/flexipages/Aura_Interoperability.flexipage-meta.xml  We couldn't retrieve the design time component information for component c:pubsubContactList.
force-app/main/default/flexipages/Composition.flexipage-meta.xml            We couldn't retrieve the design time component information for component c:compositionBasics.
force-app/main/default/flexipages/Contact_Record_Page.flexipage-meta.xml    We couldn't retrieve the design time component information for component c:recordFormDynamicContact.
force-app/main/default/flexipages/Data_Service.flexipage-meta.xml           We couldn't retrieve the design time component information for component c:lds.
force-app/main/default/flexipages/Events.flexipage-meta.xml                 We couldn't retrieve the design time component information for component c:eventSimple.
force-app/main/default/flexipages/Hello.flexipage-meta.xml                  We couldn't retrieve the design time component information for component c:hello.
force-app/main/default/flexipages/Misc_Techniques.flexipage-meta.xml        We couldn't retrieve the design time component information for component c:miscGetUserId.
force-app/main/default/flexipages/Navigation.flexipage-meta.xml             We couldn't retrieve the design time component information for component c:navToHome.
force-app/main/default/flexipages/Parent_to_Child.flexipage-meta.xml        We couldn't retrieve the design time component information for component c:apiProperty.
force-app/main/default/flexipages/Pub_Sub.flexipage-meta.xml                We couldn't retrieve the design time component information for component c:pubsubSearchBar.
N/A                                                                         Main markup cannot be empty. If you are trying to delete the Lightning definition bundle, directly delete the bundle instead.
N/A                                                                         Main markup cannot be empty. If you are trying to delete the Lightning definition bundle, directly delete the bundle instead.
N/A                                                                         Main markup cannot be empty. If you are trying to delete the Lightning definition bundle, directly delete the bundle instead.
force-app/main/default/tabs/Misc_Techniques.tab-meta.xml                    In field: flexiPage - no FlexiPage named Misc_Techniques found
force-app/main/default/tabs/Navigation.tab-meta.xml                         In field: flexiPage - no FlexiPage named Navigation found
force-app/main/default/tabs/Events.tab-meta.xml                             In field: flexiPage - no FlexiPage named Events found
force-app/main/default/tabs/Data_Service.tab-meta.xml                       In field: flexiPage - no FlexiPage named Data_Service found
force-app/main/default/tabs/Composition.tab-meta.xml                        In field: flexiPage - no FlexiPage named Composition found
force-app/main/default/tabs/Aura_Interoperability.tab-meta.xml              In field: flexiPage - no FlexiPage named Aura_Interoperability found
force-app/main/default/tabs/Apex.tab-meta.xml                               In field: flexiPage - no FlexiPage named Apex found
force-app/main/default/tabs/Hello.tab-meta.xml                              In field: flexiPage - no FlexiPage named Hello found
force-app/main/default/tabs/Parent_to_Child.tab-meta.xml                    In field: flexiPage - no FlexiPage named Parent_to_Child found
force-app/main/default/tabs/Pub_Sub.tab-meta.xml                            In field: flexiPage - no FlexiPage named Pub_Sub found
force-app/main/default/tabs/Wire.tab-meta.xml                               In field: flexiPage - no FlexiPage named Wire found
force-app/main/default/tabs/X3rd_Party_Libs.tab-meta.xml                    In field: flexiPage - no FlexiPage named X3rd_Party_Libs found
force-app/main/default/applications/LWC_Recipes.app-meta.xml                In field: tab - no CustomTab named Hello found
force-app/main/default/permissionsets/recipes.permissionset-meta.xml        In field: tab - no CustomTab named Apex found
N/A                                                                         We couldn't validate your component. Review it and try again. The following code has invalid references which caused safe validation failure. AuraDefinition [
                                                                            id:null
                                                                            deftype:null
                                                                            format:null
                                                                            source:
                                                                            null] (0:0)
N/A                                                                         We couldn't validate your component. Review it and try again. The following code has invalid references which caused safe validation failure. AuraDefinition [
                                                                            id:null
                                                                            deftype:null
                                                                            format:null
                                                                            source:
                                                                            null] (0:0)
N/A                                                                         We couldn't validate your component. Review it and try again. The following code has invalid references which caused safe validation failure. AuraDefinition [
                                                                            id:null
                                                                            deftype:null
                                                                            format:null
                                                                            source:
                                                                            null] (0:0)

**Comment by zaynelt** [comment]
There are sometimes delays with My Domain propagation with pre-release scratch org instances, and this can cause deployments of Lightning component bundles to fail. Can you try making another scratch org, and first run 'sfdx force:org:open' to verify that My Domain is correctly propagated (the scratch org should open in Lightning Setup) before attempting to push?

**Comment by Sheing** [comment]
Just cloned and pushed from scratch, works fine for me. Make sure you remember to `setdefaultusername` if you have multiple scratch org setup.
