### ISSUE TITLE
Generating my own RelatedList

### ISSUE THREAD

**Issue by jpmonette** [trailheadapps/lwc-recipes#70]
I'm trying to replicate the look & feel of a related list. I started to use `<lightning-datatable/>` - however, it looks different from the standard ones (headers are different, there's the action button in the header...).

In order to work around this, I tried to manually build my own using standard HTML5 markup:

`<table class="slds-table slds-table_cell-buffer slds-table_bordered">...`

Everything went smooth, until I tried to output my field data in the right way:

```html
<lightning-record-view-form key={row.Id} record-id={row.Id} object-api-name="OpportunityLineItem">
    <tr class="slds-hint-parent">
        <template for:each={columns} for:item="column">
            <td key={column.fieldApiName}>
                <lightning-output-field field-name={column} variant="label-hidden"></lightning-output-field>
            </td>
        </template>
    </tr>
</lightning-record-view-form>
```

The challenge here is that the `<tr>` and `<td/>` tags are outputted as text. I could use a `<div/>` instead, but, of course, they won't have the SLDS styling applied.

Is there an alternative way to output a field value, formatted based on its data type?

**Comment by kevinv11n** [comment]
This will not be performant: each row contains a `lightning-record-view-form` which loads records individually.

Salesforce has not published a component that displays a related list. As you note it’s quite complex. For example, 
1. Bulk load the records in a single call. 
2. Support pagination. 
3. Map all field types to a presentation component. 
4. Use a presentation component (like `lightning-data-table`) to display each row 
5. Handle data changes. 
Not to mention edit/inline edit and so forth. 

If you want to proceed I recommend using the structure hinted at above:
1. Bulk load the records in a single call. Load the object metadata. 
2. Use `lightning-data-table` to display the data 
3. Map object field types to `lightning-data-table` cell types.

**Comment by muenzpraeger** [comment]
Here‘s a community example using `lightning-datatable`.

https://github.com/dancinllama/Related-List-LWC
