### ISSUE TITLE
code refactoring

### ISSUE THREAD

**Issue by pgajek2** [trailheadapps/lwc-recipes#715]
### Summary

I would like to improve code quality by making it simple and reducing the code amount. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pgajek2** [comment]
@satyasekharcvb did you have a chance to take a look at my PR?

**Comment by satyasekharcvb** [comment]
Hi @pgajek2, Thank you so much for the PR. I have approved the changes and the PR will be merged soon.

**Comment by satyasekharcvb** [comment]
PR#716 merged
