### ISSUE TITLE
The lightning/navigation mock cannot be reset

### ISSUE THREAD

**Issue by AdamTReineke** [trailheadapps/lwc-recipes#720]
### Summary

The `lightning/navigation` mock cannot be reset, so later tests in the same file will read state from earlier tests in the same file.

 I'll be submitting a PR that fixes this.

### Salesforce Org Type

Scratch Org

### Steps To Reproduce

1. Add identical tests before and after a navigation test that verify pageReference is undefined (aka, no navigation happened).
1. Run the tests.

For example, here's a commit that does this: https://github.com/trailheadapps/lwc-recipes/commit/da77ad518aeda26a7be6856c8a13fa3a695b15ea

### Current Behavior

The test fails because the pageReference is NOT undefined in the second test.

### Expected Behavior

The test passes because changes made to mocks in earlier tests should not persist.

### Relevant Log Output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by satyasekharcvb** [comment]
Fixed with your PR #721. Thank you, @AdamTReineke!
