### ISSUE TITLE
When we are trying to install in to Developer edition, getting  error called "no Custom Field 'CleanStatus' on Contact object".

### ISSUE THREAD

**Issue by vino2vijay** [trailheadapps/lwc-recipes#73]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot or code snippets_.

**Comment by muenzpraeger** [comment]
The DE template as outlined in the README works just fine.

Please provide further information as above described.

**Comment by vino2vijay** [comment]
Please find the attached document,
 
![capture](https://user-images.githubusercontent.com/7345471/53753803-26406080-3e80-11e9-93fb-42940632ef70.PNG)

**Comment by muenzpraeger** [comment]
So that’s happening with the DE org that’s provided for sign up in the README

**Comment by vino2vijay** [comment]
> So that’s happening with the DE org that’s provided for sign up in the README?

able to install now. When I create new DE org based on your comment, it works fine. 

Seems it might not work for old DE org. I have created that org somewhat around 2012. 

Thanks,
