### ISSUE TITLE
Add a new lwc example for auto populate fields on page 

### ISSUE THREAD

**Issue by chandra2ravi** [trailheadapps/lwc-recipes#74]
@kevinv11n @zaynelt @muenzpraeger 
Created a new competitor(custom object) from opportunity page and need to fill some fields on the page from opportunity object. But not working in lwc.
Opportunity is master for a competitor

lightning-record-edit-form object-api-name={competitorObject} onsuccess={handleCompetitorCreated}>
lightning-input-field field-name={opportunityField} value={**recordId**}></lightning-input-field>
</lightning-record-edit-form>

![image](https://user-images.githubusercontent.com/93057/53759148-4292cc00-3e85-11e9-8faa-f1c5d40af8a9.png)

**Comment by muenzpraeger** [comment]
@chandra2ravi For general questions around Lightning Web Components, that don't relate to recipes, or are not requests for new recipes, please use the existing channels:

Trailblazer Community - Lightning Web Components
https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000LlT2SAK

Salesforce Developer Forums
https://developer.salesforce.com/forums

Salesforce Stackexchange
(https://salesforce.stackexchange.com/

**Comment by chandra2ravi** [comment]
@muenzpraeger I have updated my query i think i didn't ask properly.

**Comment by muenzpraeger** [comment]
@chandra2ravi The recipes purpose is showcasing how a single feature of LWC is build. You're request goes beyond that purpose, and is more a built solution resulting in a combination of different recipes.

`uiRecordApi` in the LWC documentation should give you a good head start.

**Comment by chandra2ravi** [comment]
Thanks!   @muenzpraeger 
I managed the above passing recordid and using uiRecordApi, but if you add recipe it's useful for others.
