### ISSUE TITLE
Pass custom object to Apex

### ISSUE THREAD

**Issue by damonshaw** [trailheadapps/lwc-recipes#75]
Please add examples passing parameters to Apex,

Thanks to calling Aura "Lightning" for the last few years and now calling lwc "lightning" using google to find answers is almost useless.

I tried the creating an Account example found here which passes an object, but that doesn't work for my wrapper and Apex only receives a null
https://trailhead.salesforce.com/content/learn/modules/lightning-web-components-for-aura-developers/work-with-salesforce-data?trail_id=build-lightning-web-components

I've tried variations of the contact search example to try and pass a string but only got a console error.

I finally stumbled across a youtube video that happened to have the solution buried in it where I have to pass an object containing my custom object converted to a string.

Would have been nice to just come to the "official" lwc recipe page to get the answer.

**Comment by muenzpraeger** [comment]
Can you please show the code that’s not working for you? Otherwise it’s just guessing.

**Comment by damonshaw** [comment]
I did get it working with this, however I had to search for quite some time to find the solution as other examples I found seemed to pass a single string which gave me an error, or what looks like an object however when I tried to pass my object it came through to Apex as null.

`updateSettings() {
    saveSettings({
        settings: JSON.stringify(this.settings)
    })
        .then(result => {
            console.log(JSON.stringify(result));
        })
        .catch(error => {
            console.log(JSON.stringify(error));
        });
}
`

**Comment by muenzpraeger** [comment]
@damonshaw What is your Apex parameter type? An sObject or an Apex class?

**Comment by damonshaw** [comment]
it's a custom class wrapper object,

public class Settings {
    @AuraEnabled public String message { get; set; }
    @AuraEnabled public Cron schedule { get; set; }
    @AuraEnabled public NotificationSettings apexChatterSettings { get; set; }
    @AuraEnabled public NotificationSettings apexEmailSettings { get; set; }
}

public class NotificationSettings {
    @AuraEnabled public String type { get; set; }
    @AuraEnabled public String recipient { get; set; }
    @AuraEnabled public Boolean allCoverage { get; set; }
    @AuraEnabled public Boolean coverageDrop { get; set; }
    @AuraEnabled public Integer coverageDropThreshold { get; set; }
    @AuraEnabled public Boolean coverageWarning { get; set; }
    @AuraEnabled public Integer coverageWarningThreshold { get; set; }
    @AuraEnabled public Boolean coverageFailure { get; set; }
    @AuraEnabled public Boolean failingTest { get; set; }
}

**Comment by muenzpraeger** [comment]
@damonshaw I just rebuild your example, and it works as expected. Based on your statement that you're receiving `null` (I don't see the shape of `this.settings` here) I guess that you got the parameter name not wrapped correctly.

Here's the shape of the Apex method that I built:
`public static Boolean checkApexTypes(Settings sett) {`

This is how the object is constructed:
```
const typeTest = {
    sett: {
        message: 'some message',
        apexChatterSettings: {
            type: 'some type',
            recipient: 'some recipient',
            allCoverage: true,
            coverageDropThreshold: 111
        }
    }
};
```

And then how imperative Apex is called:
`checkTypes(typeTest)`

**Comment by muenzpraeger** [comment]
FYI @damonshaw, I'm gonna close this issue now. I'm gonna add a recipe for this use case shortly, so that there's is more clarity. Thanks for reaching out!
