### ISSUE TITLE
LibsCharts Error

### ISSUE THREAD

**Issue by brianbier** [trailheadapps/lwc-recipes#76]
When you put your scratch org in debug mode, There is there error that shows up in the console for ChartsJS only.  I can't seem to find a way to fix it.

```
aura_proddebug.js:205 Error: [LWC error]: insertBefore is disallowed in Element unless `lwc:dom="manual"` directive is used in the template.
<lightning-card>
	<c-libs-chartjs>
    at Object.logError (aura_proddebug.js:202)
    at HTMLDivElement.value (aura_proddebug.js:4686)
    at Proxy.value (aura_proddebug.js:13247)
    at l (VM50670 chart:6680)
    at Proxy.u.renderProxy (VM50670 chart:6685)
    at HTMLCanvasElement.handleEvent (aura_proddebug.js:11163)
    at HTMLCanvasElement.fnOrObj.$$lwcEventWrapper$$ (aura_proddebug.js:3825)
```

**Comment by muenzpraeger** [comment]
Yup. It’s the lib modifying the DOM. That’s not fixable (except you want to modify the chartjs code itself).

FYI @diervo

**Comment by brianbier** [comment]
@muenzpraeger Thank you. So the error is okay to ignore for now? It doesn't break anything. 

Not sure how I would modify it. I tried a few things but It always threw the error. If you have an example that would be great.

**Comment by muenzpraeger** [comment]
It’s okay. You can’t fix it. I can’t fix it. You have to ignore it.

**Comment by pradeepsubramaniam** [comment]
Hey guys not sure if you are still looking for a work around, I have a fix for this without changing chart.js

@brianbier instead adding "lwc:dom" attribute to canvas. Add it to div element

`<div lwc:dom=“manual” class=“slds-m-around_medium chart-container”></div>`

then inside the load script of chart js use.

`let canvas = document.createElement(“canvas”);
       canvas.classList.add(“chart”);
       canvas.setAttribute(“lwc:dom”, “manual”);
       element.querySelector(“.chart-container”).appendChild(canvas);
       const ctx = canvas.getContext(“2d”);`

Hope this helps

**Comment by muenzpraeger** [comment]
Thanks for the comment, @pradeepsubramaniam. That's a good solution to prevent at least the error message.

One note: the call `canvas.setAttribute(“lwc:dom”, “manual”);` is not necessary, as the outer component has already the directive set.

**Comment by pradeepsubramaniam** [comment]
I was thinking the same thing but didn't test the theory. Thanks

**Comment by jsaudino** [comment]
Thanks  @pradeepsubramaniam!!

About this `element.querySelector(“.chart-container”).appendChild(canvas);` didn't work for me, i ended up using `this.template.querySelector(“.chart-container”).appendChild(canvas);`
