### ISSUE TITLE
How can we simulate standard depended picklist scenario using JEST ?

### ISSUE THREAD

**Issue by vijaykumar8448** [trailheadapps/lwc-recipes#77]
How can we simulate standard  depended picklist scenario using JEST ?

**Comment by muenzpraeger** [comment]
Can you please post the LWC code that you’re using? Otherwise it’s only guessing.

**Comment by vijaykumar8448** [comment]
HTML
-------------
<template>
        <lightning-card
        title="People Record"
        icon-name="standard:contact"
    >
        <div class="slds-m-around_medium">
                <lightning-record-edit-form  object-api-name={objectApiName} record-id={recordId} >
            <lightning-messages></lightning-messages>
                <lightning-input-field
                    field-name={eid}
                ></lightning-input-field>

                <lightning-input-field
                    field-name={eName}
                ></lightning-input-field>

                <lightning-input-field
                    field-name={eState}
                ></lightning-input-field>

                <lightning-input-field
                    field-name={eCity}
                ></lightning-input-field>

                <div class="slds-m-top_medium">
                        <lightning-button
                            variant="brand"
                            type="submit"
                            name="save"
                            label="Save"
                        ></lightning-button>
                    </div>
                </lightning-record-edit-form>
            </div>
    
        
        </lightning-card>            
    
</template>
------------------------------
JS
-----------
import { LightningElement ,api} from 'lwc';
import Eid from '@salesforce/schema/Employee__c.id';
import NAME_FIELD from '@salesforce/schema/Employee__c.Name';
import State_FIELD from '@salesforce/schema/Employee__c.State__c';
import City_FIELD from '@salesforce/schema/Employee__c.City__c';


export default class OppCreate_testCase extends LightningElement {
    eid = Eid;
    eName = NAME_FIELD;
    eState = State_FIELD;
    eCity = City_FIELD;

    @api recordId;
    @api objectApiName;
}

---------------------
metadata xml 
--------------
<?xml version="1.0" encoding="UTF-8"?>
<LightningComponentBundle xmlns="http://soap.sforce.com/2006/04/metadata" fqn="oppCreate_testCase">
    <apiVersion>45.0</apiVersion>
     <isExposed>true</isExposed>
    <targets>
        <target>lightning__RecordPage</target>
    </targets>
    <targetConfigs>
        <targetConfig targets="lightning__RecordPage">
            <objects>
                <object>Employee__c</object>
            </objects>
        </targetConfig>
    </targetConfigs>
</LightningComponentBundle>

------------------------------------------
This is more like 
https://github.com/trailheadapps/lwc-recipes/tree/master/force-app/main/default/lwc/recordEditFormStaticContact

But I want simulate for depended picklist change . Thanks in Advance .

**Comment by muenzpraeger** [comment]
That’s the wrong approach. You want to test a base componet. But that’s not how you test.

You only unit test your own component. Not the functionality of children of the component.

**Comment by vijaykumar8448** [comment]
[attachemt for full files .txt](https://github.com/trailheadapps/lwc-recipes/files/2937788/attachemt.for.full.files.txt)
 @muenzpraeger  Please find this file for full code .

**Comment by muenzpraeger** [comment]
See here the test that you should write, or re-use. You have to test that you pass the right config. 

https://github.com/trailheadapps/lwc-recipes/blob/master/force-app/main/default/lwc/recordEditFormStaticContact/__tests__/recordEditFormStaticContact.test.js
