### ISSUE TITLE
Jest Test Example for Loading a Static Resource

### ISSUE THREAD

**Issue by cnaccio** [trailheadapps/lwc-recipes#78]
Would it be possible to get an example showing how to use jest to load a static resource and actually have that static resource loaded. The current example doesn't actually load the static resource, it just mocks the loadScript call. Thanks!

**Comment by muenzpraeger** [comment]
`lwc-jest` provides automocks for that, as shown here, which are sufficient for unit testing:

https://github.com/trailheadapps/lwc-recipes/blob/master/force-app/main/default/lwc/miscStaticResource/__tests__/miscStaticResource.test.js

If you want functionality beyond that I suggest to open an issue on that repo:
https://github.com/salesforce/lwc-jest

Out of curiosity - what would you want to test on the static resource?

**Comment by cnaccio** [comment]
Hey there, thanks so much for the quick reply. So in our specific use case, we using the element resize detector (https://github.com/wnr/element-resize-detector) to help smooth out the loading of lightning UI input components on a custom LWC modal form component we've created. This library helps us know when the lightning input components are done rendering, so we can hide our skeleton illustrations. 

But in a general sense, say we were using the lodash library. Wouldn't we want to have that library loaded so that the component created during testing worked as expected?

Thanks so much for your help!

_P.S. Here's some details from my colleague who worked on the custom form component_

> The lightning-input-field component says it's rendered before it actually is, but it only triggers the renderedCallback hook one time.. so it fires the renderedCallback only once when it's an empty div. It ends up looking really crappy. The resize library listens for changes on the parent element because it gets bigger and bigger as the lightning-input-fields finish rendering

**Comment by muenzpraeger** [comment]
Depending on the library that you use you can implement it as ES6 modules, and then re-use it directly (not as static resource) like here:

https://github.com/trailheadapps/lwc-recipes/tree/master/force-app/main/default/lwc/ldsUtils

**Comment by cnaccio** [comment]
Ah perfect. That will work. Thanks so much!

**Comment by trevor-bliss** [comment]
I personally wouldn't be opposed to adding an example where we import and use the real library rather than the mock. ChartJs or D3 may not be the best examples though.

**Comment by muenzpraeger** [comment]
I have today played with moment.js. That should do it.

**Comment by muenzpraeger** [comment]
https://github.com/trailheadapps/lwc-recipes/tree/master/force-app/main/default/lwc/libsMomentjs

@cnaccio
