### ISSUE TITLE
Add back the original Modal recipe component

### ISSUE THREAD

**Issue by ctcforce** [trailheadapps/lwc-recipes#796]
### Summary

The new `modal` standard LWC component has a so far unfixed bug that prevents it from dispatching custom events.
It also can't leverage the Navigation Mixin

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by satyasekharcvb** [comment]
Hi @ctcforce, [Dispatching custom event from the modal component works as expected when LWS is enabled](https://developer.salesforce.com/docs/component-library/bundle/lightning-modal/documentation). To capture modal events, you can attach them in the .open() method invoked by the component that opens the modal. You can use Navigation Mixin in the event handler. If you have more questions, you may please reach me on my email - ssekhar@salesforce.com.  Thank you!
