### ISSUE TITLE
In the  apiSetterGetter recipe there is no setter neither getter functions what makes it a bit confusing

### ISSUE THREAD

**Issue by egraells** [trailheadapps/lwc-recipes#797]
### Summary

Running through the excellence recipes repo I jumped to the _apiSetterGetter_ recipe. If I am not mistaken this should be an example on how to use getter and setter functions as they are explained here https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.js_props_getters_setters but I could not find one.

### Suggested Solution

In my opinion, it would  be clearer to provide an example of a getter and a setter functions in the code.

### Alternative Solutions

I might be wrong as I am not an expert in LWC, please just accept my apologies if I am wrong.
Thanks a million for these great recipes 🥇

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by satyasekharcvb** [comment]
Hi @egraells , we are glad you like recipes. This example illustrates how to pass the data from parent to child and how to use the getter and setter. In this recipe, the child component todoList(highlighted below) has the getter and setter. 
![Screenshot 2023-05-02 at 7 44 06 AM](https://user-images.githubusercontent.com/31529847/235565619-eae91994-ef9e-4d90-bf02-174d3d4b4428.png)
You can check the code [here](https://github.com/trailheadapps/lwc-recipes/blob/main/force-app/main/default/lwc/todoList/todoList.js). Thank you!
