### ISSUE TITLE
Popover events doesn't trigger eventClick function on FullCalendar

### ISSUE THREAD

**Issue by saysonjerald** [trailheadapps/lwc-recipes#805]
### Summary

I have 6 events in 1 day so it show up on popover view and I have no problems with that whoever the popover automatically close when I click either one of those events inside the popover.  

### Salesforce Org Type

Scratch Org

### Current Behavior

- Popoever automatically close when one of the events is clicked.
- eventClick()  from fullcalendar didn't even triggered.

### Expected Behavior

- make events inside the popover clickable
- and eventClick() will be trigger

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by satyasekharcvb** [comment]
The current recipe showcases only the usage of third party library. The recipe will be enhanced and re-implemented once the third party components are supported on the lightning experience. Thank you!
