### ISSUE TITLE
CurrentPageReference not working in Communities

### ISSUE THREAD

**Issue by SuperPluck** [trailheadapps/lwc-recipes#86]
Using the wireCurrentPageReference recipe in a community always returns the pageRef as _undefined_

Also, it appears that the state is not sent as query parameters (not sure, because we could not read the pageRef).

**Comment by muenzpraeger** [comment]
`lightning-navigation` is currently not a supported experience for Communities.

https://developer.salesforce.com/docs/component-library/bundle/lightning-navigation/documentation

**Comment by MuzaffarMahmood** [comment]
What about salesforce mobile app is it supported in mobile app?
