### ISSUE TITLE
Record Picker - MultiValue component

### ISSUE THREAD

**Issue by SimonKempf** [trailheadapps/lwc-recipes#892]
### Summary

We would like to have a simple implementation of the Record Picker component (lightning-record-picker) where user can select a multiple records and see them displayed in pill-container
![Screenshot 2024-01-10 at 14 44 45](https://github.com/trailheadapps/lwc-recipes/assets/17006909/d2a18e2a-3945-4c51-ba83-252817d8c5bf)

### Suggested Solution

Record Picker emitting a change event with selected record ID ([lightning-record-picker](https://developer.salesforce.com/docs/component-library/bundle/lightning-record-picker/documentation))
The wrapper component calls GraphQL wire to retrieve the selected record details.
Lightning-pill-container is used to display selected records in pills

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pozil** [comment]
Thanks Simon and team. Great contribution. I merged the PR.
