### ISSUE TITLE
Package Installation Error

### ISSUE THREAD

**Issue by suresh83kumar** [trailheadapps/lwc-recipes#90]
Getting below error while installing package in my developer org.
This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.

Your request to install package "LWCRecipes Spring 19" was unsuccessful. None of the data or setup information in your salesforce.com organization was affected.

If your install continues to fail, contact Salesforce CRM Support through your normal channels and provide the following information.

Organization: Gmail (00D90000000cRG6)
User: Suresh (00590000000adC7)
Package: LWCRecipes (04tB0000000KAfT)
Error Number: 718476680-58815 (-656211600)
Problem:

1. (recipes) In field: field - no CustomField named Contact.CleanStatus found
recipes: In field: field - no CustomField named Contact.CleanStatus found

**Comment by muenzpraeger** [comment]
See #73
