### ISSUE TITLE
Unable to install/run Jest tests for lwc-recipes project

### ISSUE THREAD

**Issue by tfuda** [trailheadapps/lwc-recipes#92]
### Summary

Unable to install the npm packages required to run the Jest unit tests for the lwc-recipes project

### Steps To Reproduce:

I've checked out the lwc-recipes repo and deployed the code to a new scratch org. I then try to execute an "npm install" to install the packages required to execute Jest unit tests for the project. I first tried executing the "npm install" using node version 10.15.3 (latest stable node 10 version). This results in the following error:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.12 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.12 install script.
```
I Googled this problem and discovered this StackExchange post: https://salesforce.stackexchange.com/questions/248796/lwc-jest-installation-fails. I followed the suggestion here and downgraded to node 8.15.1 (latest stable node 8 version). This resulted in the following error:
```
> lwc-recipes@0.1.0 postinstall D:\Users\Tom\Development\lwc-recipes
> node bin/check-version.js



Required node version >= 10.13.0 not satisfied with current version v8.15.1.


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lwc-recipes@0.1.0 postinstall: `node bin/check-version.js`
npm ERR! Exit status 1
```
I even tried version 10.13.0, and that resulted in the same error as 10.15.3. 

### Expected result

I expected the npm packages to install successfully, and Jest unit tests to run.

### Actual result

Can't install the packages required to run the tests.

**Comment by muenzpraeger** [comment]
Can you please check if the error, with node 10, is the same as mentioned here (assuming you run on Windows):

https://github.com/salesforce/lwc-jest/issues/42

**Comment by tfuda** [comment]
I am on Windows, and the error I get with node 10 is the same as in the post you reference in your comment. In reading that issue thread, it sounds like the suggestion is to run the command `npm install --global --production windows-build-tools`. I will try that and let you know what happens.

**Comment by muenzpraeger** [comment]
I also suggest to directly run an npm install for deasync. That will install the 0.1.14 version. Maybe it’s also a dependency issue within `lwc-jest` with the 0.1.12 version.

**Comment by tfuda** [comment]
Ok, after running `npm install --global --production windows-build-tools` against node version 10.15.3, I was able to get a successful Jest test run of the lwc-recipes project. I didn't try installing deasync 0.1.14, since installing the windows-build-tools seems to have done the trick (at least for me). Thanks.
