### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by lmbugua852** [trailheadapps/lwc-recipes#926]
### Summary

Tried to install this in a sandbox but got an error.

### Salesforce Org Type

Sandbox

### Steps To Reproduce

Install as unlocked package in sandbox.

### Current Behavior

WHERE Name LIKE :key AND Picture__c != ^ ERROR at Row:4:Column:19 field 'Name' can not be filtered in a query call | ContactController: WHERE Name LIKE :key AND Picture__c != ^ ERROR at Row:4:Column:19 field 'Name' can not be filtered in a query call

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by satyasekharcvb** [comment]
Hi @lmbugua852, I tried installing this and I am unable to reproduce the error. Can you please check if there is any existing custom field called picture__c in your contact object. Please reach me if you are still unable to install it. Thank you!
