### ISSUE TITLE
Add Reactive Example

### ISSUE THREAD

**Issue by pbattisson** [trailheadapps/lwc-recipes#97]
It would be good to see an example of a reactive property within the example as this is not covered.

I propose an example that shows retrieving the default record type Id for an object and then the pick list values for a pick list on the object to show the reactive record type id property.

**Comment by muenzpraeger** [comment]
Hi @pbattisson,

reactive properties for `wire` are covered in a few recipes, for example [apexWireMethodWithParams](https://github.com/trailheadapps/lwc-recipes/blob/3036d3f3e3eed938fb70850c38c96b9c0f401fe7/force-app/main/default/lwc/apexWireMethodWithParams/apexWireMethodWithParams.js#L10), [wireGetObjectInfo](https://github.com/trailheadapps/lwc-recipes/blob/3036d3f3e3eed938fb70850c38c96b9c0f401fe7/force-app/main/default/lwc/wireGetObjectInfo/wireGetObjectInfo.js#L9), or [wireGetRecordUser](https://github.com/trailheadapps/lwc-recipes/blob/3036d3f3e3eed938fb70850c38c96b9c0f401fe7/force-app/main/default/lwc/wireGetRecordUser/wireGetRecordUser.js#L12), to name a few.

Is there anything that these recipes don't cover?

**Comment by pbattisson** [comment]
Actually they look good, weirdly when I did a search they didn't show up - could we tag them to mention reactive properties some way?

**Comment by muenzpraeger** [comment]
That's tough somehow. Because `@api` and `@track` are reactive properties by definition.
