### ISSUE TITLE
Add SVG file example for using the standard icons in lwc

### ISSUE THREAD

**Issue by chandra2ravi** [trailheadapps/lwc-recipes#99]
Can you please add an example(svg) for using the standard icons in lwc.
https://www.lightningdesignsystem.com/icons/

**Comment by muenzpraeger** [comment]
The standard icons are represented via the `lightning-icon` base component.

https://developer.salesforce.com/docs/component-library/bundle/lightning-icon

What else would be needed?

**Comment by patmcclellan** [comment]
Change the fill color of standard icons.



Pat McClellan
415-793-1337
Chief Lightning Officer
Proton 7 Group

**Comment by muenzpraeger** [comment]
That’s documented in the base components documentation, use the `class` attribute in combination with the available SLDS classes for that.

https://developer.salesforce.com/docs/component-library/bundle/lightning-icon/documentation

**Comment by chandra2ravi** [comment]
we can use in the html file as per the document. I didn't find any documentation for how to use in .SVG file.
component.svg @muenzpraeger

**Comment by muenzpraeger** [comment]
If you want to use the standard icons as SVG you've to pull them from the Lightning Design System [website](lightningdesignsystem.com), and implement them manually.
